In [ ]:
## Python course for data scientists in a moderate level, supported by Wagatsuma Lab@Kyutech 
#
# The MIT License (MIT): Copyright (c) 2022 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
#
# # @Time    : 2023-02-03 
# # @Author  : Hiroaki Wagatsuma
# # @Site    : https://github.com/hirowgit/2B3_python_owl_logic_database_course
# # @IDE     : Python 3.9.16 (main, Dec  7 2022, 10:15:43) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
# # @File    : lec2_step3.py 


In [1]:
import numpy as np
import re
from pyvis.network import Network
import networkx as nx
import matplotlib.pyplot as plt

In [9]:
# completed version of making a network of class nodes

Nd=2
Sd=3

def dictMerge(d1,d2):
    d1c=d1.copy()
    d2c=d2.copy()
    cKey=list(set(list(d1c.keys()))&set(list(d2c.keys())))
    for key in cKey:
        tmpL=d1c[key]+d2c[key]
        d2c[key]=list(set(tmpL))
    d1c.update(d2c)
    return(d1c)

def genTree(S):
    Nkey = re.search(r'\d+', S)
    Skey = re.search(r'[a-zA-Z]+', S)
    if len(S)>=7:
        return({})
    else:
        numK=int(Nkey.group())
#         numK=numK+1
        strK=Skey.group()
        strKn=ord(strK[-1])+1
        strK_pre=strK
        strK=chr(strKn)
        res=[strK+'1']
        res={}
        listT=[]
#         Nd_tmp=np.random.randint(Nd)+1
#         Sd_tmp=np.random.randint(Sd)+1
        Nd_tmp=Nd
        Sd_tmp=Sd
        
#         paramR=np.random.randint(Sd,size=[Nd_tmp,Sd_tmp])
        paramR=np.array([[0,1],[0,1]])
        for k in range(len(paramR)):
            tmpS=[chr(ord('A')+d)+str(k+1) for d in list(set(paramR[k]))]
            for d in tmpS:
                res=dictMerge(res,genTree(strK_pre+d))
                listT=listT+[strK_pre+d]
        
        d0={}
        if numK==1:
            d0[S]=listT
        resD=dictMerge(d0,res)
        return(resD)

outDict=genTree('A1')
print(outDict)

{'A1': ['AA1', 'AB1', 'AA2', 'AB2'], 'AA1': ['AAA1', 'AAB1', 'AAA2', 'AAB2'], 'AAA1': ['AAAB2', 'AAAA1', 'AAAB1', 'AAAA2'], 'AAAA1': ['AAAAA1', 'AAAAA2', 'AAAAB1', 'AAAAB2'], 'AAAAA1': ['AAAAAB1', 'AAAAAB2', 'AAAAAA2', 'AAAAAA1'], 'AAAAB1': ['AAAABA1', 'AAAABA2', 'AAAABB1', 'AAAABB2'], 'AAAB1': ['AAABA2', 'AAABA1', 'AAABB2', 'AAABB1'], 'AAABA1': ['AAABAA1', 'AAABAA2', 'AAABAB1', 'AAABAB2'], 'AAABB1': ['AAABBA2', 'AAABBB2', 'AAABBA1', 'AAABBB1'], 'AAB1': ['AABB2', 'AABA1', 'AABA2', 'AABB1'], 'AABA1': ['AABAB1', 'AABAB2', 'AABAA1', 'AABAA2'], 'AABAA1': ['AABAAA1', 'AABAAA2', 'AABAAB2', 'AABAAB1'], 'AABAB1': ['AABABA2', 'AABABB2', 'AABABA1', 'AABABB1'], 'AABB1': ['AABBB1', 'AABBA1', 'AABBB2', 'AABBA2'], 'AABBA1': ['AABBAA1', 'AABBAB2', 'AABBAB1', 'AABBAA2'], 'AABBB1': ['AABBBA2', 'AABBBB1', 'AABBBB2', 'AABBBA1'], 'AB1': ['ABA1', 'ABB1', 'ABA2', 'ABB2'], 'ABA1': ['ABAB2', 'ABAB1', 'ABAA1', 'ABAA2'], 'ABAA1': ['ABAAA1', 'ABAAA2', 'ABAAB1', 'ABAAB2'], 'ABAAA1': ['ABAAAB2', 'ABAAAA1', 'ABAAAA

In [12]:
maxN=max(lenR)

backTraceNP=np.empty(len(topL),dtype=object)
for k in range(len(topL)):
    st=topL[k]
    tmpL=[st]
    Skeys = [key for key, val in outDict.items() if st in val]
    while len(Skeys)>0:
        tmpL=Skeys+tmpL
        st=Skeys[0]
        Skeys = [key for key, val in outDict.items() if st in val]
    backTraceNP[k]=tmpL

matchN=np.full(len(topL),0,dtype=int)
matchL_full=np.empty(len(topL),dtype=object)
    
for k in range(len(topL)):
    matchL=set(backTraceNP[k])&set(otherL)
    matchL_full[k]=list(matchL)+[topL[k]]
    matchN[k]=len(matchL)
#     print(len(matchL))

key=np.where(matchN>0)
matchL_full2=matchL_full[key].tolist()    
matchL_flat=sum(matchL_full2,[])
print(matchN)
print(matchL_full2)
print(matchL_flat)

mergeN=np.full([len(matchL_full2),len(matchL_full2)],0,dtype=int)
mergeL=[]
for j1 in range(len(matchL_full2)):
    for j2 in range(j1,len(matchL_full2)):
        if j1!=j2:
            dupN=len(set(matchL_full2[j1])&set(matchL_full2[j2]))
            mergeN[j1,j2]=dupN
            if dupN>0:
                mergeL=mergeL+[list(set(matchL_full2[j1]+matchL_full2[j2]))]
                print((j1,j2))
            

# mergeN=np.triu(mergeN)            
print(mergeN)
print(mergeL)
mLN=[len(d) for d in mergeL]
print(mLN)

keyMax=np.argmax(mLN)

MaxList=mergeL[keyMax]
MaxList
# np.where(mergeN==np.max(np.max(mergeN)))
# np.max(np.max(mergeN))

[0 2 1 0]
[['ABB1', 'ABBB1', 'ABBBAA1'], ['AAABB1', 'AAABBB2']]
['ABB1', 'ABBB1', 'ABBBAA1', 'AAABB1', 'AAABBB2']
[[0 0]
 [0 0]]
[]
[]


ValueError: attempt to get argmax of an empty sequence

In [10]:
nodeSize=10
conWidth=2
rNd=40

network = Network(
    height="500px",  # default param = 500px
    width="2000px",  # default param = 500px
    notebook=True,  # For jupyter notebook, it should be True
    bgcolor="rgb(255,255,255)",  # default color = "#ffffff" "rgb(255,255,255)"
    directed=True,   # directional graph = True, non- directinal graph = False
)
str2num=lambda S: [ord(d)-ord('A')+1 if not(str.isdecimal(d)) else int(d) for d in S ]

all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
# rLIst=np.random.randint(len(all_Item),size=rNd)

# matchL_flat

keyList=list(outDict.keys())
for k in range(len(all_Item)):
    nd= int("".join(map(str, str2num(all_Item[k]))))
    if k in rLIst:
        colName="lightblue"
    else:
        colName="gray"
    if all_Item[k] in matchL_flat:
        colName="pink"
    if all_Item[k] in MaxList:
        colName="red"
    network.add_node(n_id=nd,label=all_Item[k], shape="box",size=nodeSize,color =colName)
    
for k in range(len(outDict)):
    nodeMn= int("".join(map(str, str2num(keyList[k]))))
#     print(keyList[k])
    nodeS=outDict[keyList[k]]
#     print(nodeS)
    nodeSn=[ int("".join(map(str, str2num(d)))) for d in nodeS]
#     print(nodeSn)
    for j in range(len(nodeSn)):
        network.add_edge(nodeMn,nodeSn[j], width=conWidth,smooth="dynamic")

# output the results in the HTML format (and visualization in the jupyter notebook panel)
network.show("class_list6.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


NameError: name 'MaxList' is not defined

In [5]:
rNd=10
all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
rLIst=np.random.randint(len(all_Item),size=rNd)
print(rLIst)

[ 25 103   8  45  49  12  27  95  61  92]


In [11]:
8 in rLIst

False

In [6]:
all_Item_np=np.array(all_Item)
itemR_np=all_Item_np[rLIst]
itemR=all_Item_np[rLIst].tolist()
lenR=[len(d) for d in itemR]
lenR_np=np.array(lenR)
print(lenR)
key = np.argsort(lenR) 
key2=key[::-1]
sortedD_np=itemR_np[key2]
sortedD=itemR_np[key2].tolist()
sortedN=lenR_np[key2]

maxN=max(lenR)
topKey=np.where(sortedN==maxN)

topL=sortedD_np[topKey]
otherL=sortedD_np[topKey[0][-1]+1:].tolist()

print(sortedD)
print(sortedN)
print(topKey)

print(topL)
print(otherL)
# otherL

[4, 5, 6, 7, 7, 5, 5, 4, 7, 7]
['AABAAB2', 'ABBBAA1', 'AAABBB2', 'AABBBB1', 'AAABB1', 'ABBB1', 'AAAA1', 'ABBB2', 'ABB1', 'AAB2']
[7 7 7 7 6 5 5 5 4 4]
(array([0, 1, 2, 3]),)
['AABAAB2' 'ABBBAA1' 'AAABBB2' 'AABBBB1']
['AAABB1', 'ABBB1', 'AAAA1', 'ABBB2', 'ABB1', 'AAB2']


In [46]:
AABABB1
AAAAA1

18

In [36]:
# AABAAA2

outDict.items() 

dict_items([('A1', ['AA1', 'AB1', 'AA2', 'AB2']), ('AA1', ['AAA1', 'AAB1', 'AAA2', 'AAB2']), ('AAA1', ['AAAA1', 'AAAB1', 'AAAB2', 'AAAA2']), ('AAAA1', ['AAAAB2', 'AAAAA1', 'AAAAB1', 'AAAAA2']), ('AAAAA1', ['AAAAAB2', 'AAAAAA1', 'AAAAAB1', 'AAAAAA2']), ('AAAAB1', ['AAAABA2', 'AAAABB2', 'AAAABB1', 'AAAABA1']), ('AAAB1', ['AAABA1', 'AAABA2', 'AAABB2', 'AAABB1']), ('AAABA1', ['AAABAB2', 'AAABAB1', 'AAABAA2', 'AAABAA1']), ('AAABB1', ['AAABBA1', 'AAABBB2', 'AAABBA2', 'AAABBB1']), ('AAB1', ['AABB1', 'AABB2', 'AABA2', 'AABA1']), ('AABA1', ['AABAB1', 'AABAA2', 'AABAA1', 'AABAB2']), ('AABAA1', ['AABAAA2', 'AABAAB2', 'AABAAB1', 'AABAAA1']), ('AABAB1', ['AABABB1', 'AABABA1', 'AABABA2', 'AABABB2']), ('AABB1', ['AABBB1', 'AABBA2', 'AABBA1', 'AABBB2']), ('AABBA1', ['AABBAB1', 'AABBAA1', 'AABBAB2', 'AABBAA2']), ('AABBB1', ['AABBBA2', 'AABBBA1', 'AABBBB2', 'AABBBB1']), ('AB1', ['ABA1', 'ABB1', 'ABA2', 'ABB2']), ('ABA1', ['ABAA1', 'ABAB1', 'ABAB2', 'ABAA2']), ('ABAA1', ['ABAAB1', 'ABAAA2', 'ABAAA1', 'AB

In [50]:
matchN=[]
matchN[0]=1

IndexError: list assignment index out of range

In [7]:
maxN=max(lenR)

backTraceNP=np.empty(len(topL),dtype=object)
for k in range(len(topL)):
    st=topL[k]
    tmpL=[st]
    Skeys = [key for key, val in outDict.items() if st in val]
    while len(Skeys)>0:
        tmpL=Skeys+tmpL
        st=Skeys[0]
        Skeys = [key for key, val in outDict.items() if st in val]
    backTraceNP[k]=tmpL

matchN=np.full(len(topL),0,dtype=int)
matchL_full=np.empty(len(topL),dtype=object)
    
for k in range(len(topL)):
    matchL=set(backTraceNP[k])&set(otherL)
    matchL_full[k]=list(matchL)+[topL[k]]
    matchN[k]=len(matchL)
#     print(len(matchL))

key=np.where(matchN>0)
matchL_full2=matchL_full[key].tolist()    
matchL_flat=sum(matchL_full2,[])
print(matchN)
print(matchL_full2)
print(matchL_flat)

mergeN=np.full([len(matchL_full2),len(matchL_full2)],0,dtype=int)
mergeL=[]
for j1 in range(len(matchL_full2)):
    for j2 in range(j1,len(matchL_full2)):
        if j1!=j2:
            dupN=len(set(matchL_full2[j1])&set(matchL_full2[j2]))
            mergeN[j1,j2]=dupN
            if dupN>0:
                mergeL=mergeL+[list(set(matchL_full2[j1]+matchL_full2[j2]))]
                print((j1,j2))
            

# mergeN=np.triu(mergeN)            
print(mergeN)
print(mergeL)
mLN=[len(d) for d in mergeL]
print(mLN)

keyMax=np.argmax(mLN)

MaxList=mergeL[keyMax]
MaxList
# np.where(mergeN==np.max(np.max(mergeN)))
# np.max(np.max(mergeN))

[0 2 1 0]
[['ABB1', 'ABBB1', 'ABBBAA1'], ['AAABB1', 'AAABBB2']]
['ABB1', 'ABBB1', 'ABBBAA1', 'AAABB1', 'AAABBB2']
[[0 0]
 [0 0]]
[]
[]


ValueError: attempt to get argmax of an empty sequence

In [65]:
matchL_full2

[['AAAA1', 'AAAAB1', 'AAAABA1'],
 ['ABAAB1', 'ABAABA1'],
 ['AAAA1', 'AAAAA1', 'AAAAAB2'],
 ['ABB1', 'ABBA1', 'ABBABA2'],
 ['AAAA1', 'AAAAB1', 'AAAABA1'],
 ['ABB1', 'ABBA1', 'ABBAAB2']]

In [3]:
nodeSize=10
conWidth=2
rNd=40

network = Network(
    height="500px",  # default param = 500px
    width="1000px",  # default param = 500px
    notebook=True,  # For jupyter notebook, it should be True
    bgcolor="rgb(255,255,255)",  # default color = "#ffffff" "rgb(255,255,255)"
    directed=True,   # directional graph = True, non- directinal graph = False
)
str2num=lambda S: [ord(d)-ord('A')+1 if not(str.isdecimal(d)) else int(d) for d in S ]

all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
# rLIst=np.random.randint(len(all_Item),size=rNd)

matchL_flat

keyList=list(outDict.keys())
for k in range(len(all_Item)):
    nd= int("".join(map(str, str2num(all_Item[k]))))
    if k in rLIst:
        colName="lightblue"
    else:
        colName="gray"
    if all_Item[k] in matchL_flat:
        colName="pink"
    if all_Item[k] in MaxList:
        colName="red"
    network.add_node(n_id=nd,label=all_Item[k], shape="box",size=nodeSize,color =colName)
    
for k in range(len(outDict)):
    nodeMn= int("".join(map(str, str2num(keyList[k]))))
#     print(keyList[k])
    nodeS=outDict[keyList[k]]
#     print(nodeS)
    nodeSn=[ int("".join(map(str, str2num(d)))) for d in nodeS]
#     print(nodeSn)
    for j in range(len(nodeSn)):
        network.add_edge(nodeMn,nodeSn[j], width=conWidth,smooth="dynamic")

# output the results in the HTML format (and visualization in the jupyter notebook panel)
network.show("class_list5.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


NameError: name 'matchL_flat' is not defined

In [8]:
nodeSize=10
conWidth=2
rNd=40

network = Network(
    height="500px",  # default param = 500px
    width="1000px",  # default param = 500px
    notebook=True,  # For jupyter notebook, it should be True
    bgcolor="rgb(255,255,255)",  # default color = "#ffffff" "rgb(255,255,255)"
    directed=True,   # directional graph = True, non- directinal graph = False
)
str2num=lambda S: [ord(d)-ord('A')+1 if not(str.isdecimal(d)) else int(d) for d in S ]

all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
# rLIst=np.random.randint(len(all_Item),size=rNd)

# matchL_flat

keyList=list(outDict.keys())
for k in range(len(all_Item)):
    nd= int("".join(map(str, str2num(all_Item[k]))))
    if k in rLIst:
        colName="lightblue"
    else:
        colName="gray"
    if all_Item[k] in matchL_flat:
        colName="pink"
    if all_Item[k] in MaxList:
        colName="red"
    network.add_node(n_id=nd,label=all_Item[k], shape="box",size=nodeSize,color =colName)
    
for k in range(len(outDict)):
    nodeMn= int("".join(map(str, str2num(keyList[k]))))
#     print(keyList[k])
    nodeS=outDict[keyList[k]]
#     print(nodeS)
    nodeSn=[ int("".join(map(str, str2num(d)))) for d in nodeS]
#     print(nodeSn)
    for j in range(len(nodeSn)):
        network.add_edge(nodeMn,nodeSn[j], width=conWidth,smooth="dynamic")

# output the results in the HTML format (and visualization in the jupyter notebook panel)
network.show("class_list6.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


NameError: name 'MaxList' is not defined

In [99]:
all_Item

['AABBA1',
 'AABAA1',
 'AABB2',
 'AAABAA2',
 'AAB2',
 'AAABBB1',
 'AABAAA1',
 'ABBBBB2',
 'ABBAA2',
 'AABAB2',
 'ABAABB1',
 'ABBBBA1',
 'AAAAAA2',
 'AAB1',
 'AAAAA2',
 'AAAAB1',
 'ABBAAB2',
 'ABBBB2',
 'ABBBAA1',
 'ABAA2',
 'AA1',
 'ABBABA2',
 'AABBAB2',
 'AAAABA1',
 'AABBB1',
 'ABAB1',
 'ABBAAA1',
 'ABAA1',
 'AAAAAB2',
 'AAAAAA1',
 'AABABA1',
 'AAAABB1',
 'ABABBA2',
 'AAAABA2',
 'AAAAB2',
 'AABABB2',
 'ABAABA1',
 'AABBAA1',
 'ABAAAB2',
 'ABBAB1',
 'ABBBB1',
 'ABBBAB1',
 'ABA1',
 'AABAAA2',
 'AAABB2',
 'ABABB2',
 'AAABB1',
 'A1',
 'ABBAAA2',
 'ABBBAA2',
 'ABAB2',
 'AABAAB1',
 'AABABA2',
 'AAAB1',
 'ABAABA2',
 'AABAB1',
 'AAABAA1',
 'ABABAB2',
 'ABBB1',
 'AAABA1',
 'AB1',
 'ABAAAA2',
 'AABBAB1',
 'ABABA2',
 'AABBBB1',
 'ABBBA1',
 'AAAA1',
 'AABABB1',
 'ABBAAB1',
 'ABBBA2',
 'ABBBBB1',
 'ABBABA1',
 'AAABBA2',
 'ABABA1',
 'AAABAB2',
 'AAABBB2',
 'AAAB2',
 'AAA1',
 'AABBB2',
 'ABAAAB1',
 'ABABAA2',
 'ABABBA1',
 'AAAABB2',
 'ABBAB2',
 'AABBAA2',
 'AAA2',
 'AAABBA1',
 'AABBBA1',
 'AABBA2',
 