In [ ]:
## Python course for data scientists in a moderate level, supported by Wagatsuma Lab@Kyutech 
#
# The MIT License (MIT): Copyright (c) 2022 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
#
# # @Time    : 2023-02-03 
# # @Author  : Hiroaki Wagatsuma
# # @Site    : https://github.com/hirowgit/2B3_python_owl_logic_database_course
# # @IDE     : Python 3.9.16 (main, Dec  7 2022, 10:15:43) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
# # @File    : lec2_step3.py 


In [1]:
import numpy as np
import re
from pyvis.network import Network
import networkx as nx
import matplotlib.pyplot as plt

In [2]:
# completed version of making a network of class nodes

Nd=2
Sd=3

def dictMerge(d1,d2):
    d1c=d1.copy()
    d2c=d2.copy()
    cKey=list(set(list(d1c.keys()))&set(list(d2c.keys())))
    for key in cKey:
        tmpL=d1c[key]+d2c[key]
        d2c[key]=list(set(tmpL))
    d1c.update(d2c)
    return(d1c)

def genTree(S):
    Nkey = re.search(r'\d+', S)
    Skey = re.search(r'[a-zA-Z]+', S)
    if len(S)>=7:
        return({})
    else:
        numK=int(Nkey.group())
#         numK=numK+1
        strK=Skey.group()
        strKn=ord(strK[-1])+1
        strK_pre=strK
        strK=chr(strKn)
        res=[strK+'1']
        res={}
        listT=[]
#         Nd_tmp=np.random.randint(Nd)+1
#         Sd_tmp=np.random.randint(Sd)+1
        Nd_tmp=Nd
        Sd_tmp=Sd
        
#         paramR=np.random.randint(Sd,size=[Nd_tmp,Sd_tmp])
        paramR=np.array([[0,1],[0,1]])
        for k in range(len(paramR)):
            tmpS=[chr(ord('A')+d)+str(k+1) for d in list(set(paramR[k]))]
            for d in tmpS:
                res=dictMerge(res,genTree(strK_pre+d))
                listT=listT+[strK_pre+d]
        
        d0={}
        if numK==1:
            d0[S]=listT
        resD=dictMerge(d0,res)
        return(resD)

outDict=genTree('A1')
print(outDict)

{'A1': ['AA1', 'AB1', 'AA2', 'AB2'], 'AA1': ['AAA1', 'AAB1', 'AAA2', 'AAB2'], 'AAA1': ['AAAB2', 'AAAA2', 'AAAB1', 'AAAA1'], 'AAAA1': ['AAAAB2', 'AAAAA1', 'AAAAA2', 'AAAAB1'], 'AAAAA1': ['AAAAAA2', 'AAAAAA1', 'AAAAAB1', 'AAAAAB2'], 'AAAAB1': ['AAAABA1', 'AAAABB1', 'AAAABB2', 'AAAABA2'], 'AAAB1': ['AAABB2', 'AAABA1', 'AAABA2', 'AAABB1'], 'AAABA1': ['AAABAA1', 'AAABAB2', 'AAABAB1', 'AAABAA2'], 'AAABB1': ['AAABBB2', 'AAABBA1', 'AAABBA2', 'AAABBB1'], 'AAB1': ['AABA2', 'AABB1', 'AABA1', 'AABB2'], 'AABA1': ['AABAA2', 'AABAB1', 'AABAB2', 'AABAA1'], 'AABAA1': ['AABAAB2', 'AABAAA1', 'AABAAA2', 'AABAAB1'], 'AABAB1': ['AABABA2', 'AABABB1', 'AABABA1', 'AABABB2'], 'AABB1': ['AABBB2', 'AABBA2', 'AABBA1', 'AABBB1'], 'AABBA1': ['AABBAA1', 'AABBAA2', 'AABBAB1', 'AABBAB2'], 'AABBB1': ['AABBBA2', 'AABBBA1', 'AABBBB2', 'AABBBB1'], 'AB1': ['ABA1', 'ABB1', 'ABA2', 'ABB2'], 'ABA1': ['ABAA1', 'ABAB2', 'ABAA2', 'ABAB1'], 'ABAA1': ['ABAAA1', 'ABAAB2', 'ABAAB1', 'ABAAA2'], 'ABAAA1': ['ABAAAB2', 'ABAAAA1', 'ABAAAA

In [3]:
rNd=20
all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
rLIst=np.random.randint(len(all_Item),size=rNd)
print(rLIst)

all_Item_np=np.array(all_Item)
itemR_np=all_Item_np[rLIst]
itemR=all_Item_np[rLIst].tolist()
lenR=[len(d) for d in itemR]
lenR_np=np.array(lenR)
print(lenR)
key = np.argsort(lenR) 
key2=key[::-1]
sortedD_np=itemR_np[key2]
sortedD=itemR_np[key2].tolist()
sortedN=lenR_np[key2]

maxN=max(lenR)
topKey=np.where(sortedN==maxN)

topL=sortedD_np[topKey]
otherL=sortedD_np[topKey[0][-1]+1:].tolist()

print(sortedD)
print(sortedN)
print(topKey)

print(topL)
print(otherL)
# otherL

[ 99  43  11  99  82  92 121  33  63   4  49  67 103  67 118  76  70  59
  13   6]
[4, 5, 6, 4, 7, 7, 6, 7, 7, 7, 6, 7, 5, 7, 7, 6, 7, 7, 6, 3]
['AABBAB2', 'ABAAAA2', 'AABAAA2', 'ABBABA2', 'AAAABB1', 'AABBBA1', 'ABAAAA2', 'ABABAA1', 'ABBBAB1', 'AABABB1', 'AAABB1', 'ABBBB1', 'AAAAB1', 'ABABA2', 'ABAAA2', 'AAAA2', 'AABA1', 'ABA2', 'ABA2', 'AB1']
[7 7 7 7 7 7 7 7 7 7 6 6 6 6 6 5 5 4 4 3]
(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),)
['AABBAB2' 'ABAAAA2' 'AABAAA2' 'ABBABA2' 'AAAABB1' 'AABBBA1' 'ABAAAA2'
 'ABABAA1' 'ABBBAB1' 'AABABB1']
['AAABB1', 'ABBBB1', 'AAAAB1', 'ABABA2', 'ABAAA2', 'AAAA2', 'AABA1', 'ABA2', 'ABA2', 'AB1']


In [232]:
rNd=40
all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
rLIst=np.random.randint(len(all_Item),size=rNd)
print(all_Item)
print(rLIst)

[ 90 113 115  39  82  64  92 124 113 100  88 106  91  78  85  62  41 111
 116 117  89  20   3  36  22 119   5  75  36  91 108  24  16  54  76 123
 100  75  57  89]


In [4]:
rNd=40
all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
rLIst=np.random.randint(len(all_Item),size=rNd)
print(rLIst)

all_Item_np=np.array(all_Item)
itemR_np=all_Item_np[rLIst]
itemR=all_Item_np[rLIst].tolist()
lenR=[len(d) for d in itemR]
lenR_np=np.array(lenR)
print(lenR)
key = np.argsort(lenR) 
key2=key[::-1]
sortedD_np=itemR_np[key2]
sortedD=itemR_np[key2].tolist()
sortedN=lenR_np[key2]

maxN=max(lenR)
topKey=np.where(sortedN==maxN)

topL=sortedD_np[topKey]
otherL=sortedD_np[topKey[0][-1]+1:].tolist()

maxN=max(lenR)

backTraceNP=np.empty(len(topL),dtype=object)
for k in range(len(topL)):
    st=topL[k]
    tmpL=[st]
    Skeys = [key for key, val in outDict.items() if st in val]
    while len(Skeys)>0:
        tmpL=Skeys+tmpL
        st=Skeys[0]
        Skeys = [key for key, val in outDict.items() if st in val]
    backTraceNP[k]=tmpL

matchN=np.full(len(topL),0,dtype=int)
matchN2=np.full(len(topL),0,dtype=int)
boolP_full=np.empty(len(topL),dtype=object)
matchL_full=np.empty(len(topL),dtype=object)
    
for k in range(len(topL)):
    matchL=set(backTraceNP[k])&set(otherL)
    boolP=np.full(len(backTraceNP[k]),False,dtype=bool)
    for d1 in matchL:
        key=np.where(np.array(backTraceNP[k]) ==d1)[0]
        boolP[key]=True
    boolP_full[k]=boolP    
    matchL_full[k]=list(matchL)+[topL[k]]
    matchN[k]=len(matchL)
    matchN2[k]=len(backTraceNP[k])
#     print(len(matchL))

key=np.where(matchN>0)
matchL_full2=matchL_full[key].tolist()    
matchL_flat=sum(matchL_full2,[])
print(matchN)
print(matchL_full2)
print(matchL_flat)
print('---')
mergeN=np.full([len(matchL_full2),len(matchL_full2)],0,dtype=int)
mergeL=[]
mergeL2=[]
boolL2=[]
# sflag=True
lenL=[]
for j1 in range(len(matchL_full2)):
    for j2 in range(j1,len(matchL_full2)):
        if j1!=j2:
            dupL=set(matchL_full2[j1])&set(matchL_full2[j2])           
            dupN=len(dupL)
            mergeN[j1,j2]=dupN
            if dupN>0:
                mergeL=mergeL+[list(set(matchL_full2[j1]+matchL_full2[j2]))]
                mergeL2=mergeL2+[backTraceNP[j1]+backTraceNP[j2]]
                boolL2=boolL2+[boolP_full[j1].tolist()+boolP_full[j2].tolist()]
#                 if sflag:
#                     boolL2=np.array([[boolP_full[j1],boolP_full[j2]]])
#                     sflag=False
#                 else:
#                     boolL2=np.vstack([boolL2,np.array([[boolP_full[j1],boolP_full[j2]]])])
                lenL=lenL+[max([len(d) for d in dupL] )]
#                 print(mergeL2)
#                 print((j1,j2))
            

# mergeN=np.triu(mergeN)            
# print(mergeN)
# print(mergeL)
mLN=[len(d) for d in mergeL]
# print(mLN)

keyMax=np.argmax(mLN)
print(keyMax)
MaxList=mergeL[keyMax]
MaxList2=mergeL2[keyMax]
MaxBool=boolL2[keyMax]



# MaxList
# np.where(mergeN==np.max(np.max(mergeN)))
# np.max(np.max(mergeN))
print(len(mergeL))
print(len(lenL))
print(len(boolL2))
print(lenL)


MaxBool_NP=np.array(MaxBool)
pickT=set(MaxList2)&set(topL)
keyL=[]
for d in pickT:
    key=np.where(np.array(MaxList2)==d)[0]
    print(key)
    keyL=keyL+key.tolist()
    MaxBool_NP[key]=True
keyL=sorted(keyL+[0])
# print(MaxBool_NP)
# print(keyL)

print('---')
tRatio=[]
for k in range(len(keyL)-1):
    bL=MaxBool_NP[keyL[k]:keyL[k+1]+1]
    st=np.where(bL)[0][0]
    bL=bL[st:]
    
    tNum=len(np.where(bL)[0])
    tRatio=tRatio+[tNum/len(bL)]
#     print(tNum)
#     print(tRatio)
#     print(bL)
# MaxBool
tRatioAll=np.mean(tRatio)

print(tRatioAll)

#

[ 60  11  90  61 101  71  78  31  28  57  89  15   0   6  58 119  36 121
  55 121 111  87  11 121  76  43  16  18  49  72  85  21 114  35  79 100
  36  35 123  11]
[7, 6, 5, 7, 6, 7, 7, 7, 7, 6, 5, 6, 6, 3, 7, 6, 6, 6, 7, 6, 7, 7, 6, 6, 6, 5, 7, 7, 6, 7, 5, 7, 4, 4, 5, 7, 6, 4, 4, 6]
[1 2 2 2 2 2 3 1 4 1 1 4 1 3 1]
[['AABA1', 'AABABA1'], ['AAA1', 'AAAA1', 'AAAABA2'], ['AB1', 'ABB1', 'ABBAAA1'], ['AB1', 'ABAAA1', 'ABAAAA1'], ['AB1', 'ABB1', 'ABBABB1'], ['AAABB1', 'AAA1', 'AAABBA1'], ['AAAAA1', 'AAA1', 'AAAA1', 'AAAAAA1'], ['AABB1', 'AABBBB2'], ['ABBB1', 'ABBBB1', 'AB1', 'ABB1', 'ABBBBA1'], ['AB1', 'ABABBB1'], ['AABB1', 'AABBBB1'], ['ABBB1', 'ABBBB1', 'AB1', 'ABB1', 'ABBBBA2'], ['AABB1', 'AABBAA1'], ['ABBB1', 'AB1', 'ABB1', 'ABBBAB2'], ['AB1', 'ABAABA2']]
['AABA1', 'AABABA1', 'AAA1', 'AAAA1', 'AAAABA2', 'AB1', 'ABB1', 'ABBAAA1', 'AB1', 'ABAAA1', 'ABAAAA1', 'AB1', 'ABB1', 'ABBABB1', 'AAABB1', 'AAA1', 'AAABBA1', 'AAAAA1', 'AAA1', 'AAAA1', 'AAAAAA1', 'AABB1', 'AABBBB2', 'ABBB1', 'ABBBB1', '

In [238]:
len(all_Item)

125

In [239]:
rNd/len(all_Item)

0.32

In [5]:
# random generation of entities againt the generated network

rNd=40
all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
rLIst=np.random.randint(len(all_Item),size=rNd)
print(rLIst)

#===4===

all_Item_np=np.array(all_Item)
itemR_np=all_Item_np[rLIst]
itemR=all_Item_np[rLIst].tolist()
lenR=[len(d) for d in itemR]
lenR_np=np.array(lenR)
print(lenR)
key = np.argsort(lenR) 
key2=key[::-1]
sortedD_np=itemR_np[key2]
sortedD=itemR_np[key2].tolist()
sortedN=lenR_np[key2]

maxN=max(lenR)
topKey=np.where(sortedN==maxN)
#======

#===5===
topL=sortedD_np[topKey]
otherL=sortedD_np[topKey[0][-1]+1:].tolist()

backTraceNP=np.empty(len(topL),dtype=object)
for k in range(len(topL)):
    st=topL[k]
    tmpL=[st]
    Skeys = [key for key, val in outDict.items() if st in val]
    while len(Skeys)>0:
        tmpL=Skeys+tmpL
        st=Skeys[0]
        Skeys = [key for key, val in outDict.items() if st in val]
    backTraceNP[k]=tmpL

#======

#===6===    
matchN=np.full(len(topL),0,dtype=int)
matchN2=np.full(len(topL),0,dtype=int)
boolP_full=np.empty(len(topL),dtype=object)
matchL_full=np.empty(len(topL),dtype=object)

for k in range(len(topL)):
    matchL=set(backTraceNP[k])&set(otherL)
    boolP=np.full(len(backTraceNP[k]),False,dtype=bool)
    for d1 in matchL:
        key=np.where(np.array(backTraceNP[k]) ==d1)[0]
        boolP[key]=True
    boolP_full[k]=boolP    
    matchL_full[k]=list(matchL)+[topL[k]]
    matchN[k]=len(matchL)
    matchN2[k]=len(backTraceNP[k])

key=np.where(matchN>0)
matchL_full2=matchL_full[key].tolist()    
matchL_flat=sum(matchL_full2,[])
print(matchN)
print(matchL_full2)
print(matchL_flat)

#======

#===7&8===
mergeN=np.full([len(matchL_full2),len(matchL_full2)],0,dtype=int)
mergeL=[]
mergeL2=[]
boolL2=[]
# sflag=True
lenL=[]
for j1 in range(len(matchL_full2)):
    for j2 in range(j1,len(matchL_full2)):
        if j1!=j2:
            dupL=set(matchL_full2[j1])&set(matchL_full2[j2])           
            dupN=len(dupL)
            mergeN[j1,j2]=dupN
            if dupN>0:
                mergeL=mergeL+[list(set(matchL_full2[j1]+matchL_full2[j2]))]
                mergeL2=mergeL2+[backTraceNP[j1]+backTraceNP[j2]]
                boolL2=boolL2+[boolP_full[j1].tolist()+boolP_full[j2].tolist()]
                lenL=lenL+[max([len(d) for d in dupL] )]
            
mLN=[len(d) for d in mergeL]
keyMax=np.argmax(mLN)
MaxList=mergeL[keyMax]
MaxList2=mergeL2[keyMax]
MaxBool=boolL2[keyMax]

print(keyMax)
print(len(mergeL))
print(len(lenL))
print(len(boolL2))
print(lenL)
#======

#===9===

MaxBool_NP=np.array(MaxBool)
pickT=set(MaxList2)&set(topL)
keyL=[]
for d in pickT:
    key=np.where(np.array(MaxList2)==d)[0]
    print(key)
    keyL=keyL+key.tolist()
    MaxBool_NP[key]=True
keyL=sorted(keyL+[0])

tRatio=[]
for k in range(len(keyL)-1):
    bL=MaxBool_NP[keyL[k]:keyL[k+1]+1]
    st=np.where(bL)[0][0]
    bL=bL[st:]
    
    tNum=len(np.where(bL)[0])
    tRatio=tRatio+[tNum/len(bL)]
tRatioAll=np.mean(tRatio)

print(tRatioAll)

[ 89  83  70   9 108  37  90  36  17 124  31  45  22  60  51   6  61  86
  94  30  55  93  27  96  22  94  13  95  19  69  82  23  33  32  56 118
  30 109  12  77]
[5, 6, 7, 7, 5, 4, 5, 6, 7, 7, 7, 6, 7, 7, 7, 3, 7, 7, 7, 6, 7, 7, 4, 6, 7, 7, 6, 7, 7, 3, 7, 3, 7, 7, 7, 7, 6, 7, 5, 7]
[1 1 1 1 1 1 2 2 1 2 2 1 1 1 2 1 1 1 1 2 3 2 3 1]
[['AB1', 'ABBABA1'], ['AA1', 'AAAAAB2'], ['AA1', 'AABAAA1'], ['AB1', 'ABBBAB2'], ['AA1', 'AABAAB1'], ['AA1', 'AAAAAA2'], ['AA1', 'AAAAB1', 'AAAABA2'], ['ABA1', 'AB1', 'ABAABA2'], ['AB1', 'ABBABB2'], ['AA1', 'AAAB1', 'AAABBB1'], ['ABA1', 'AB1', 'ABAABB2'], ['AA1', 'AAAAAB2'], ['AA1', 'AAAAAA2'], ['AA1', 'AABABA1'], ['ABA1', 'AB1', 'ABAABA1'], ['AA1', 'AABAAB2'], ['AA1', 'AABABA2'], ['AA1', 'AABAAA2'], ['AB1', 'ABBBAB1'], ['AA1', 'AAAAB1', 'AAAABB1'], ['ABA1', 'AB1', 'ABABA1', 'ABABAB1'], ['AA1', 'AAAB1', 'AAABBA2'], ['ABA1', 'AB1', 'ABABA1', 'ABABAA1'], ['AB1', 'ABBBBB2']]
['AB1', 'ABBABA1', 'AA1', 'AAAAAB2', 'AA1', 'AABAAA1', 'AB1', 'ABBBAB2', 'AA1', 'AABAA

In [342]:
len(all_Item)

125

In [6]:
# random generation of entities againt the generated network

# rNd=40
def detectImportantSeries(rNd):
    all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
    rLIst=np.random.randint(len(all_Item),size=rNd)
#     print(rLIst)

    #===4===

    all_Item_np=np.array(all_Item)
    itemR_np=all_Item_np[rLIst]
    itemR=all_Item_np[rLIst].tolist()
    lenR=[len(d) for d in itemR]
    lenR_np=np.array(lenR)
#     print(lenR)
    key = np.argsort(lenR) 
    key2=key[::-1]
    sortedD_np=itemR_np[key2]
    sortedD=itemR_np[key2].tolist()
    sortedN=lenR_np[key2]

    maxN=max(lenR)
    topKey=np.where(sortedN==maxN)
    #======

    #===5===
    topL=sortedD_np[topKey]
    otherL=sortedD_np[topKey[0][-1]+1:].tolist()

    backTraceNP=np.empty(len(topL),dtype=object)
    for k in range(len(topL)):
        st=topL[k]
        tmpL=[st]
        Skeys = [key for key, val in outDict.items() if st in val]
        while len(Skeys)>0:
            tmpL=Skeys+tmpL
            st=Skeys[0]
            Skeys = [key for key, val in outDict.items() if st in val]
        backTraceNP[k]=tmpL

    #======

    #===6===    
    matchN=np.full(len(topL),0,dtype=int)
    matchN2=np.full(len(topL),0,dtype=int)
    boolP_full=np.empty(len(topL),dtype=object)
    matchL_full=np.empty(len(topL),dtype=object)

    for k in range(len(topL)):
        matchL=set(backTraceNP[k])&set(otherL)
        boolP=np.full(len(backTraceNP[k]),False,dtype=bool)
        for d1 in matchL:
            key=np.where(np.array(backTraceNP[k]) ==d1)[0]
            boolP[key]=True
        boolP_full[k]=boolP    
        matchL_full[k]=list(matchL)+[topL[k]]
        matchN[k]=len(matchL)
        matchN2[k]=len(backTraceNP[k])

    key=np.where(matchN>0)
    matchL_full2=matchL_full[key].tolist()    
    matchL_flat=sum(matchL_full2,[])
    #======

    #===7&8===
    mergeN=np.full([len(matchL_full2),len(matchL_full2)],0,dtype=int)
    mergeL=[]
    mergeL2=[]
    boolL2=[]
    # sflag=True
    lenL=[]
    for j1 in range(len(matchL_full2)):
        for j2 in range(j1,len(matchL_full2)):
            if j1!=j2:
                dupL=set(matchL_full2[j1])&set(matchL_full2[j2])           
                dupN=len(dupL)
                mergeN[j1,j2]=dupN
                if dupN>0:
                    mergeL=mergeL+[list(set(matchL_full2[j1]+matchL_full2[j2]))]
                    mergeL2=mergeL2+[backTraceNP[j1]+backTraceNP[j2]]
                    boolL2=boolL2+[boolP_full[j1].tolist()+boolP_full[j2].tolist()]
                    lenL=lenL+[max([len(d) for d in dupL] )]

    mLN=[len(d) for d in mergeL]
    if len(mLN)>0:
        keyMax=np.argmax(mLN)
        MaxList=mergeL[keyMax]
        MaxList2=mergeL2[keyMax]
        MaxBool=boolL2[keyMax]

        #===9===

        MaxBool_NP=np.array(MaxBool)
        pickT=set(MaxList2)&set(topL)
        keyL=[]
        for d in pickT:
            key=np.where(np.array(MaxList2)==d)[0]
    #         print(key)
            keyL=keyL+key.tolist()
            MaxBool_NP[key]=True
        keyL=sorted(keyL+[0])

        tRatio=[]
        for k in range(len(keyL)-1):
            bL=MaxBool_NP[keyL[k]:keyL[k+1]+1]
            st=np.where(bL)[0][0]
            bL=bL[st:]

            tNum=len(np.where(bL)[0])
            tRatio=tRatio+[tNum/len(bL)]
        tRatioAll=np.mean(tRatio)
        
        sList=sorted(mLN)
        sListNP=np.array(sList)

        dNP=np.abs(np.diff(np.array(sList)))
        dDiff=np.where(dNP>0)[0]
        stL=np.append(np.array([0]),dDiff+1)
        endL=np.append(dDiff,len(sList)-1)
        summaryD=np.array([sListNP[stL], (endL-stL+1)])
    else:
        tRatioAll=0
        summaryD=[]
    return([tRatioAll,summaryD])
    
paraD=[10, 20, 30, 40,50,60,70,80,90,100]    
headerSt=''
for d in paraD:  

    resList=[]    
    j=0
    distNumL=np.full(d,0,dtype=int)
    while j<100:
        resAll=detectImportantSeries(d)
        res=resAll[0]
        
        if res>0:
            distL=resAll[1]
            for k2 in range(len(distL[0])):
                k3=distL[0,k2]
                distNumL[k3]=distNumL[k3]+distL[1,k2]
            
            distNumL2=distNumL[:np.where(distNumL>0)[0][-1]+1]
#             print(distNumL2)
            distNumL3=np.array([np.arange(len(distNumL2)),distNumL2]).T
            filename='dist'+str(d)+'.csv'
            np.savetxt(filename, distNumL3 ,header='n,count',  delimiter=',')
                
            resList=resList+[res]
            j=j+1
    
    if d==paraD[0]:
        headerSt='rNd='+str(d)
        resList_full=np.array([resList])
    else:
        headerSt=headerSt+',rNd='+str(d)
        resList_full=np.vstack([resList_full,np.array([resList])])
        
# print(resList)

filename='anaData.csv'
np.savetxt(filename, resList_full.T ,header=headerSt,  delimiter=',')

In [356]:
distNumL

array([    0,     0,   261,  2026,  6495, 13760, 18550, 19632, 14212,
        7211,  2417,   258,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0])

In [338]:
distNumL3.T

array([[   0,    0],
       [   1,    0],
       [   2,  203],
       [   3, 2077],
       [   4, 3887],
       [   5, 4119],
       [   6, 3081],
       [   7, 1440],
       [   8,  409],
       [   9,   76],
       [  10,   22]])

In [349]:
distNumL3/100


array([[0.0000e+00, 0.0000e+00],
       [1.0000e-02, 0.0000e+00],
       [2.0000e-02, 2.6100e+00],
       [3.0000e-02, 2.0260e+01],
       [4.0000e-02, 6.4950e+01],
       [5.0000e-02, 1.3760e+02],
       [6.0000e-02, 1.8550e+02],
       [7.0000e-02, 1.9632e+02],
       [8.0000e-02, 1.4212e+02],
       [9.0000e-02, 7.2110e+01],
       [1.0000e-01, 2.4170e+01],
       [1.1000e-01, 2.5800e+00]])

In [350]:
mLN

[6,
 6,
 5,
 6,
 5,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 6,
 6,
 6,
 5,
 4,
 6,
 5,
 4,
 6,
 4,
 4,
 3,
 5,
 5,
 5,
 6,
 5,
 5,
 5,
 6,
 6,
 5,
 4,
 6,
 3,
 4,
 4,
 5,
 5,
 5,
 6,
 5,
 5,
 5,
 6,
 7,
 8,
 8,
 7,
 8,
 8,
 7,
 6,
 6,
 7,
 8,
 7,
 6,
 7,
 8,
 6,
 8,
 7,
 7,
 7,
 5,
 5,
 7,
 5,
 7,
 6,
 5,
 5,
 6,
 7,
 5,
 5,
 6,
 7,
 3,
 6,
 7,
 8,
 6,
 7,
 8,
 7,
 7,
 8,
 6,
 8,
 7,
 8,
 7,
 6,
 7,
 7,
 8,
 6,
 7,
 8,
 7,
 7,
 8,
 6,
 8,
 7,
 8,
 7,
 5,
 7,
 6,
 5,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 7,
 6,
 6,
 6,
 5,
 6,
 7,
 4,
 7,
 6,
 5,
 6,
 6,
 7,
 4,
 6,
 6,
 7,
 5,
 8,
 6,
 8,
 7,
 6,
 5,
 7,
 8,
 6,
 4,
 7,
 8,
 5,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 4,
 4,
 6,
 7,
 8,
 7,
 7,
 8,
 6,
 8,
 7,
 8,
 7,
 6,
 7,
 7,
 6,
 5,
 6,
 6,
 7,
 4,
 6,
 6,
 7,
 5,
 6,
 7,
 8,
 7,
 6,
 7,
 8,
 6,
 8,
 7,
 6,
 7,
 6,
 6,
 6,
 7,
 4,
 7,
 6,
 6,
 6,
 7,
 5,
 6,
 6,
 7,
 5,
 5,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 4,
 4,
 4,
 5,
 7,
 8,
 6,
 5,
 7,
 8,
 5,
 7,
 6,
 7,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 6,
 5,


In [335]:
print(distNumL)
distNumL2=distNumL[:np.where(distNumL>0)[0][-1]+1]
print(distNumL2)
np.array([np.arange(len(distNumL2)),distNumL2])

[ 0  0  4 29  8  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0]
[ 0  0  4 29  8]


array([[ 0,  1,  2,  3,  4],
       [ 0,  0,  4, 29,  8]])

In [322]:
for k2 in range(len(distL[0])):
    print(distL[1,k2])

4
29
8


In [324]:
distNumL=np.full(d,0,dtype=int)
distL=resAll[1]
for k2 in range(len(distL[0])):
    k3=distL[0,k2]
    distNumL[k3]=distNumL[k3]+distL[1,k2]
distNumL

array([ 0,  0,  4, 29,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [ ]:
resAll[1]

In [255]:
detectImportantSeries(d)

0.7142857142857143

In [251]:
for d in paraD:  
    print(d)

10
20
30
40
50


In [304]:
sList=sorted(mLN)
# sList2=sList[::-1]
print(sList)
sListNP=np.array(sList)

dNP=np.abs(np.diff(np.array(sList)))
dDiff=np.where(dNP>0)[0]
stL=np.append(np.array([0]),dDiff+1)
endL=np.append(dDiff,len(sList)-1)
for s,e in zip(stL,endL):
#     print((s,e))
    print(sListNP[s:e+1])
    print(e-s+1)


print(endL-stL+1)
print(sList)
print(stL)
print(endL)
np.array([sListNP[stL], (endL-stL+1)])
# (endL-stL+1)
# sListNP[stL]

[3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8]
[3 3 3]
3
[4 4 4 4 4 4 4 4 4 4]
10
[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]
20
[6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]
35
[7 7 7 7 7 7 7]
7
[8 8 8]
3
[ 3 10 20 35  7  3]
[3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8]
[ 0  3 13 33 68 75]
[ 2 12 32 67 74 77]


array([[ 3,  4,  5,  6,  7,  8],
       [ 3, 10, 20, 35,  7,  3]])

In [7]:
# random generation of entities againt the generated network

rNd=80
all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
rLIst=np.random.randint(len(all_Item),size=rNd)
print(rLIst)

#===4===

all_Item_np=np.array(all_Item)
itemR_np=all_Item_np[rLIst]
itemR=all_Item_np[rLIst].tolist()
lenR=[len(d) for d in itemR]
lenR_np=np.array(lenR)
print(lenR)
key = np.argsort(lenR) 
key2=key[::-1]
sortedD_np=itemR_np[key2]
sortedD=itemR_np[key2].tolist()
sortedN=lenR_np[key2]

maxN=max(lenR)
topKey=np.where(sortedN==maxN)
#======

#===5===
topL=sortedD_np[topKey]
otherL=sortedD_np[topKey[0][-1]+1:].tolist()

backTraceNP=np.empty(len(topL),dtype=object)
for k in range(len(topL)):
    st=topL[k]
    tmpL=[st]
    Skeys = [key for key, val in outDict.items() if st in val]
    while len(Skeys)>0:
        tmpL=Skeys+tmpL
        st=Skeys[0]
        Skeys = [key for key, val in outDict.items() if st in val]
    backTraceNP[k]=tmpL

#======

#===6===    
matchN=np.full(len(topL),0,dtype=int)
matchN2=np.full(len(topL),0,dtype=int)
boolP_full=np.empty(len(topL),dtype=object)
matchL_full=np.empty(len(topL),dtype=object)

for k in range(len(topL)):
    matchL=set(backTraceNP[k])&set(otherL)
    boolP=np.full(len(backTraceNP[k]),False,dtype=bool)
    for d1 in matchL:
        key=np.where(np.array(backTraceNP[k]) ==d1)[0]
        boolP[key]=True
    boolP_full[k]=boolP    
    matchL_full[k]=list(matchL)+[topL[k]]
    matchN[k]=len(matchL)
    matchN2[k]=len(backTraceNP[k])

key=np.where(matchN>0)
matchL_full2=matchL_full[key].tolist()    
matchL_flat=sum(matchL_full2,[])
print(matchN)
print(matchL_full2)
print(matchL_flat)

#======

#===7&8===
mergeN=np.full([len(matchL_full2),len(matchL_full2)],0,dtype=int)
mergeL=[]
mergeL2=[]
boolL2=[]
# sflag=True
lenL=[]
for j1 in range(len(matchL_full2)):
    for j2 in range(j1,len(matchL_full2)):
        if j1!=j2:
            dupL=set(matchL_full2[j1])&set(matchL_full2[j2])           
            dupN=len(dupL)
            mergeN[j1,j2]=dupN
            if dupN>0:
                mergeL=mergeL+[list(set(matchL_full2[j1]+matchL_full2[j2]))]
                mergeL2=mergeL2+[backTraceNP[j1]+backTraceNP[j2]]
                boolL2=boolL2+[boolP_full[j1].tolist()+boolP_full[j2].tolist()]
                lenL=lenL+[max([len(d) for d in dupL] )]
            
mLN=[len(d) for d in mergeL]
keyMax=np.argmax(mLN)
MaxList=mergeL[keyMax]
MaxList2=mergeL2[keyMax]
MaxBool=boolL2[keyMax]

print(keyMax)
print(len(mergeL))
print(len(lenL))
print(len(boolL2))
print(lenL)
#======

#===9===

MaxBool_NP=np.array(MaxBool)
pickT=set(MaxList2)&set(topL)
keyL=[]
for d in pickT:
    key=np.where(np.array(MaxList2)==d)[0]
    print(key)
    keyL=keyL+key.tolist()
    MaxBool_NP[key]=True
keyL=sorted(keyL+[0])

tRatio=[]
for k in range(len(keyL)-1):
    bL=MaxBool_NP[keyL[k]:keyL[k+1]+1]
    st=np.where(bL)[0][0]
    bL=bL[st:]
    
    tNum=len(np.where(bL)[0])
    tRatio=tRatio+[tNum/len(bL)]
tRatioAll=np.mean(tRatio)

print(tRatioAll)

[ 47  58 105  95 123  46  97 117  45  95   4  49  31  36 122  97  91  25
 107  22  82  47  10   9  16   4  53 105  56  17  65  64   2  64 113  46
  55 102 100  21   9 106  43  62  61 116  33 117  76  54  91  94 106  66
   4  10  92  76   7  20 104  41   5  17  10  26  35   0  27  37  57  75
  49  17   6  25  50  25   8 105]
[7, 7, 5, 7, 4, 3, 7, 7, 6, 7, 7, 6, 7, 6, 2, 7, 6, 6, 7, 7, 7, 7, 5, 7, 7, 7, 4, 5, 7, 7, 5, 6, 7, 6, 7, 3, 7, 6, 7, 7, 7, 7, 5, 4, 7, 7, 7, 7, 6, 6, 6, 7, 7, 5, 7, 5, 7, 6, 7, 7, 6, 7, 7, 7, 5, 5, 4, 6, 4, 4, 6, 7, 6, 7, 3, 6, 7, 6, 5, 5]
[5 3 3 3 2 3 3 4 3 5 4 2 3 2 3 3 3 2 4 4 2 3 4 3 4 4 4 2 3 4 4 3 5 2 4 4 3
 3 5 2 2]
[['ABA1', 'ABAB1', 'AB1', 'A1', 'ABABB1', 'ABABBB1'], ['A1', 'AAABA1', 'AAA1', 'AAABAA2'], ['A1', 'AB1', 'ABB1', 'ABBBAA2'], ['A1', 'AB1', 'ABB1', 'ABBBAB2'], ['A1', 'AAA1', 'AAAAAB1'], ['A1', 'AAB1', 'AABA1', 'AABABA2'], ['AABBA1', 'A1', 'AAB1', 'AABBAA1'], ['ABAA1', 'ABA1', 'AB1', 'A1', 'ABAABA2'], ['AABBA1', 'A1', 'AAB1', 'AABBAA2'], ['ABA1', 

In [355]:
a=sorted(mLN)
a[::-1]

[10,
 10,
 10,
 10,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,


In [10]:
outDict

{'A1': ['AA1', 'AB1', 'AA2', 'AB2'],
 'AA1': ['AAA1', 'AAB1', 'AAA2', 'AAB2'],
 'AAA1': ['AAAB2', 'AAAA2', 'AAAB1', 'AAAA1'],
 'AAAA1': ['AAAAB2', 'AAAAA1', 'AAAAA2', 'AAAAB1'],
 'AAAAA1': ['AAAAAA2', 'AAAAAA1', 'AAAAAB1', 'AAAAAB2'],
 'AAAAB1': ['AAAABA1', 'AAAABB1', 'AAAABB2', 'AAAABA2'],
 'AAAB1': ['AAABB2', 'AAABA1', 'AAABA2', 'AAABB1'],
 'AAABA1': ['AAABAA1', 'AAABAB2', 'AAABAB1', 'AAABAA2'],
 'AAABB1': ['AAABBB2', 'AAABBA1', 'AAABBA2', 'AAABBB1'],
 'AAB1': ['AABA2', 'AABB1', 'AABA1', 'AABB2'],
 'AABA1': ['AABAA2', 'AABAB1', 'AABAB2', 'AABAA1'],
 'AABAA1': ['AABAAB2', 'AABAAA1', 'AABAAA2', 'AABAAB1'],
 'AABAB1': ['AABABA2', 'AABABB1', 'AABABA1', 'AABABB2'],
 'AABB1': ['AABBB2', 'AABBA2', 'AABBA1', 'AABBB1'],
 'AABBA1': ['AABBAA1', 'AABBAA2', 'AABBAB1', 'AABBAB2'],
 'AABBB1': ['AABBBA2', 'AABBBA1', 'AABBBB2', 'AABBBB1'],
 'AB1': ['ABA1', 'ABB1', 'ABA2', 'ABB2'],
 'ABA1': ['ABAA1', 'ABAB2', 'ABAA2', 'ABAB1'],
 'ABAA1': ['ABAAA1', 'ABAAB2', 'ABAAB1', 'ABAAA2'],
 'ABAAA1': ['ABAAAB2',

In [9]:
nodeSize=10
conWidth=2
rNd=40

network = Network(
    height="500px",  # default param = 500px
    width="2000px",  # default param = 500px
    notebook=True,  # For jupyter notebook, it should be True
    bgcolor="rgb(255,255,255)",  # default color = "#ffffff" "rgb(255,255,255)"
    directed=True,   # directional graph = True, non- directinal graph = False
)
str2num=lambda S: [ord(d)-ord('A')+1 if not(str.isdecimal(d)) else int(d) for d in S ]

all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
# rLIst=np.random.randint(len(all_Item),size=rNd)

# matchL_flat

keyList=list(outDict.keys())
for k in range(len(all_Item)):
    nd= int("".join(map(str, str2num(all_Item[k]))))
    if k in rLIst:
        colName="lightblue"
    else:
        colName="gray"
    if all_Item[k] in matchL_flat:
        colName="pink"
    if all_Item[k] in MaxList:
        colName="red"
    network.add_node(n_id=nd,label=all_Item[k], shape="box",size=nodeSize,color =colName)
    
for k in range(len(outDict)):
    nodeMn= int("".join(map(str, str2num(keyList[k]))))
#     print(keyList[k])
    nodeS=outDict[keyList[k]]
#     print(nodeS)
    nodeSn=[ int("".join(map(str, str2num(d)))) for d in nodeS]
#     print(nodeSn)
    for j in range(len(nodeSn)):
        network.add_edge(nodeMn,nodeSn[j], width=conWidth,smooth="dynamic")

# output the results in the HTML format (and visualization in the jupyter notebook panel)
network.show("class_list6.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [230]:
MaxBool_NP=np.array(MaxBool)
pickT=set(MaxList2)&set(topL)
keyL=[]
for d in pickT:
    key=np.where(np.array(MaxList2)==d)[0]
    print(key)
    keyL=keyL+key.tolist()
    MaxBool_NP[key]=True
keyL=sorted(keyL+[0])
print(MaxBool_NP)
print(keyL)

print('---')
tRatio=[]
for k in range(len(keyL)-1):
    bL=MaxBool_NP[keyL[k]:keyL[k+1]+1]
    st=np.where(bL)[0][0]
    bL=bL[st:]
    
    tNum=len(np.where(bL)[0])
    tRatio=tRatio+[tNum/len(bL)]
    print(tNum)
    print(tRatio)
    print(bL)
# MaxBool
tRatioAll=np.mean(tRatio)

print(tRatioAll)

[11]
[5]
[False False False False False  True False False False False  True  True]
[0, 5, 11]
---
1
[1.0]
[ True]
3
[1.0, 0.42857142857142855]
[ True False False False False  True  True]
0.7142857142857143


In [210]:
keyL[k+1]
print(MaxBool_NP)

[False  True False False  True  True False  True  True False  True  True]


In [190]:
print(topL)
MaxList2,MaxBool,MaxList


['AABAAB2' 'ABBAAA1' 'ABBBAB1' 'AAABBB1' 'AAAABA1' 'ABBAAB2' 'AABBAB2'
 'ABBBBA2' 'AAAABA1' 'ABBBBB1' 'ABBBBB1' 'AABBAA1' 'ABBABB1' 'ABAABB1'
 'AABAAB2' 'AABBAA1' 'AABABA2' 'ABAABB2' 'AABAAA1' 'AAABAA1' 'ABBABA1'
 'ABBABA2']


(['A1',
  'AB1',
  'ABB1',
  'ABBB1',
  'ABBBB1',
  'ABBBBA2',
  'A1',
  'AB1',
  'ABA1',
  'ABAA1',
  'ABAAB1',
  'ABAABB1'],
 [False,
  True,
  False,
  False,
  True,
  False,
  False,
  True,
  True,
  False,
  True,
  False],
 ['ABAABB1', 'ABA1', 'ABBBB1', 'ABBBBA2', 'AB1', 'ABAAB1'])

In [ ]:
boolL2=np.vstack([boolL2,np.array([boolP_full[j1],boolP_full[j2]])])

In [144]:
len(matchL_full2),len(matchL_full),len(backTraceNP)

(11, 16, 16)

In [184]:
k=0
matchL=set(backTraceNP[k])&set(otherL)
boolP=np.full(len(backTraceNP[k]),False,dtype=bool)
for d1 in matchL:
    key=np.where(np.array(backTraceNP[k]) ==d1)[0]
    print(key,d1)
    boolP[key]=True
matchL,backTraceNP[k],boolP

[2] AAB1


({'AAB1'},
 ['A1', 'AA1', 'AAB1', 'AABA1', 'AABAA1', 'AABAAB2'],
 array([False, False,  True, False, False, False]))

In [186]:
for k in range(len(backTraceNP)):
    print(set(backTraceNP[k])&set(otherL))
    print(mergeL[k])
#     print(matchL_full2[k])
    print(mergeL2[k])
    print(boolL2[k])
    

{'AAB1'}
['AABBAB2', 'AAB1', 'AABAAB2']
['A1', 'AA1', 'AAB1', 'AABA1', 'AABAA1', 'AABAAB2', 'A1', 'AA1', 'AAB1', 'AABB1', 'AABBA1', 'AABBAB2']
[False, False, True, False, False, False, False, False, True, False, False, False]
{'AB1'}
['AABBAA1', 'AAB1', 'AABAAB2']
['A1', 'AA1', 'AAB1', 'AABA1', 'AABAA1', 'AABAAB2', 'A1', 'AA1', 'AAB1', 'AABB1', 'AABBA1', 'AABBAA1']
[False, False, True, False, False, False, False, False, True, False, False, False]
{'AB1'}
['AAB1', 'AABAAB2']
['A1', 'AA1', 'AAB1', 'AABA1', 'AABAA1', 'AABAAB2', 'A1', 'AA1', 'AAB1', 'AABA1', 'AABAA1', 'AABAAB2']
[False, False, True, False, False, False, False, False, True, False, False, False]
{'AAABB1'}
['AABBAA1', 'AAB1', 'AABAAB2']
['A1', 'AA1', 'AAB1', 'AABA1', 'AABAA1', 'AABAAB2', 'A1', 'AA1', 'AAB1', 'AABB1', 'AABBA1', 'AABBAA1']
[False, False, True, False, False, False, False, False, True, False, False, False]
{'AAAAB1'}
['AABABA2', 'AAB1', 'AABAAB2', 'AABAB1']
['A1', 'AA1', 'AAB1', 'AABA1', 'AABAA1', 'AABAAB2', 'A1

In [148]:
for k in range(len(backTraceNP)):
    print(set(backTraceNP[k])&set(otherL))
#     print(matchL_full2[k])
    print(backTraceNP[k])
    print(boolP_full[k])
    

{'AA1', 'AAAAB1', 'AAAA1'}
['A1', 'AA1', 'AAA1', 'AAAA1', 'AAAAB1', 'AAAABB1']
[False  True False  True  True False]
set()
['A1', 'AB1', 'ABA1', 'ABAB1', 'ABABA1', 'ABABAA2']
[False False False False False False]
{'AABA1', 'AA1'}
['A1', 'AA1', 'AAB1', 'AABA1', 'AABAA1', 'AABAAB2']
[False  True False  True False False]
{'AABA1', 'AA1'}
['A1', 'AA1', 'AAB1', 'AABA1', 'AABAB1', 'AABABB2']
[False  True False  True False False]
{'ABAA1'}
['A1', 'AB1', 'ABA1', 'ABAA1', 'ABAAA1', 'ABAAAB1']
[False False False  True False False]
{'ABABB1'}
['A1', 'AB1', 'ABA1', 'ABAB1', 'ABABB1', 'ABABBA1']
[False False False False  True False]
{'ABAA1'}
['A1', 'AB1', 'ABA1', 'ABAA1', 'ABAAA1', 'ABAAAB2']
[False False False  True False False]
set()
['A1', 'AB1', 'ABB1', 'ABBA1', 'ABBAA1', 'ABBAAA1']
[False False False False False False]
set()
['A1', 'AB1', 'ABB1', 'ABBB1', 'ABBBA1', 'ABBBAA2']
[False False False False False False]
set()
['A1', 'AB1', 'ABA1', 'ABAB1', 'ABABA1', 'ABABAA2']
[False False False Fal

In [104]:
a=a+[[matchL_full2[j1]],[matchL_full2[j2]]]
a

[[['ABBB1', 'ABBBB1', 'AB1', 'ABBBBB2']],
 [['ABBB1', 'ABBBB1', 'AB1', 'ABBBBB2']],
 [['ABBB1', 'ABBBB1', 'AB1', 'ABBBBB2']],
 [['ABBB1', 'ABBBB1', 'AB1', 'ABBBBB2']]]

In [91]:
print(mergeL2[0])

['ABBB1', 'AB1', 'ABBBAB2']


In [106]:
print(MaxList)
print(MaxList2)
print(MaxBool)

['AAB1', 'AABAAA2', 'AABAA1', 'AB1', 'A1', 'ABBABA2']
['A1', 'AB1', 'ABBABA2', 'AABAA1', 'A1', 'AAB1', 'AABAAA2']
[ True False False False False False]


In [63]:
boolP_full

array([array([ True, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([False, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([False, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([ True, False, False, False, False, False]),
       array([

In [42]:
matchN/matchN2

array([0.33333333, 0.16666667, 0.16666667, 0.16666667, 0.16666667,
       0.16666667, 0.5       , 0.16666667, 0.16666667, 0.33333333,
       0.5       , 0.33333333, 0.5       , 0.16666667, 0.16666667,
       0.33333333])

In [233]:
nodeSize=10
conWidth=2
rNd=40

network = Network(
    height="500px",  # default param = 500px
    width="1500px",  # default param = 500px
    notebook=True,  # For jupyter notebook, it should be True
    bgcolor="rgb(255,255,255)",  # default color = "#ffffff" "rgb(255,255,255)"
    directed=True,   # directional graph = True, non- directinal graph = False
)
str2num=lambda S: [ord(d)-ord('A')+1 if not(str.isdecimal(d)) else int(d) for d in S ]

all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
# rLIst=np.random.randint(len(all_Item),size=rNd)

# matchL_flat

keyList=list(outDict.keys())
for k in range(len(all_Item)):
    nd= int("".join(map(str, str2num(all_Item[k]))))
    if k in rLIst:
        colName="lightblue"
    else:
        colName="gray"
    if all_Item[k] in matchL_flat:
        colName="pink"
    if all_Item[k] in MaxList:
        colName="red"
    network.add_node(n_id=nd,label=all_Item[k], shape="box",size=nodeSize,color =colName)
    
for k in range(len(outDict)):
    nodeMn= int("".join(map(str, str2num(keyList[k]))))
#     print(keyList[k])
    nodeS=outDict[keyList[k]]
#     print(nodeS)
    nodeSn=[ int("".join(map(str, str2num(d)))) for d in nodeS]
#     print(nodeSn)
    for j in range(len(nodeSn)):
        network.add_edge(nodeMn,nodeSn[j], width=conWidth,smooth="dynamic")

# output the results in the HTML format (and visualization in the jupyter notebook panel)
network.show("class_list6.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [20]:
# all_Item