In [ ]:
## Python course for data scientists in a moderate level, supported by Wagatsuma Lab@Kyutech 
#
# The MIT License (MIT): Copyright (c) 2022 Hiroaki Wagatsuma and Wagatsuma Lab@Kyutech
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */
#
# # @Time    : 2023-02-03 
# # @Author  : Hiroaki Wagatsuma
# # @Site    : https://github.com/hirowgit/2B3_python_owl_logic_database_course
# # @IDE     : Python 3.9.16 (main, Dec  7 2022, 10:15:43) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
# # @File    : lec2_step2.py 


In [61]:
import numpy as np
import re


In [8]:
asciiN=ord('A')
asciiS=chr(asciiN)
print(asciiN)
print(asciiS)

65
A


In [9]:
S='Z'
S=='Z'

True

In [11]:
def genTree(S):
    if S=='Z':
        return(S)
    else:
        key=ord(S)+1
        res=genTree(chr(key))
        return(S+res)

genTree('A')    

'ABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [18]:
data=['A']
data.append('G')
data

['A', 'G']

In [19]:
def genTree(S):
    if S=='Z':
        return([S])
    else:
        rerutn([''])

genTree('Z')   

['Z']

In [28]:
def genTree(S):
    if S=='Z':
        return([S])
    else:
        key=ord(S)+1
        res=genTree(chr(key))
        return([S]+res)

genTree('A')


['A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z']

In [35]:
import re

S='ABC1829'
Nkey = re.search(r'\d+', S)
Skey = re.search(r'[a-zA-Z]+', S)
print(Nkey.group())
print(Skey.group())

1829
ABC


In [33]:
re.search(r'[a-zA-Z]+', S)

<re.Match object; span=(0, 3), match='ABC'>

In [37]:
def genTree(S):
    Nkey = re.search(r'\d+', S)
    Skey = re.search(r'[a-zA-Z]+', S)
    if Skey.group()=='Z':
        return([S])
    else:
        numK=int(Nkey.group())
        numK=numK+1
        strK=Skey.group()
        strKn=ord(strK)+1
        strK=chr(strKn)
        
        res=genTree(strK+str(numK))        
        
        return([S]+res)

genTree('A1')


['A1',
 'B2',
 'C3',
 'D4',
 'E5',
 'F6',
 'G7',
 'H8',
 'I9',
 'J10',
 'K11',
 'L12',
 'M13',
 'N14',
 'O15',
 'P16',
 'Q17',
 'R18',
 'S19',
 'T20',
 'U21',
 'V22',
 'W23',
 'X24',
 'Y25',
 'Z26']

In [51]:
def genTree(S):
    Nkey = re.search(r'\d+', S)
    Skey = re.search(r'[a-zA-Z]+', S)
    if Skey.group()=='Z':
        return([S])
    else:
        numK=int(Nkey.group())
        numK=numK+1
        strK=Skey.group()
        strKn=ord(strK)+1
        strK=chr(strKn)
        
        res1=genTree(strK+'1')        
        res2=genTree(strK+'2')   
        
        return([S]+res1+res2)

genTree('U1')


['U1',
 'V1',
 'W1',
 'X1',
 'Y1',
 'Z1',
 'Z2',
 'Y2',
 'Z1',
 'Z2',
 'X2',
 'Y1',
 'Z1',
 'Z2',
 'Y2',
 'Z1',
 'Z2',
 'W2',
 'X1',
 'Y1',
 'Z1',
 'Z2',
 'Y2',
 'Z1',
 'Z2',
 'X2',
 'Y1',
 'Z1',
 'Z2',
 'Y2',
 'Z1',
 'Z2',
 'V2',
 'W1',
 'X1',
 'Y1',
 'Z1',
 'Z2',
 'Y2',
 'Z1',
 'Z2',
 'X2',
 'Y1',
 'Z1',
 'Z2',
 'Y2',
 'Z1',
 'Z2',
 'W2',
 'X1',
 'Y1',
 'Z1',
 'Z2',
 'Y2',
 'Z1',
 'Z2',
 'X2',
 'Y1',
 'Z1',
 'Z2',
 'Y2',
 'Z1',
 'Z2']

In [56]:
def genTree(S):
    Nkey = re.search(r'\d+', S)
    Skey = re.search(r'[a-zA-Z]+', S)
    if Skey.group()[0]=='D':
        return([S])
    else:
        numK=int(Nkey.group())
        numK=numK+1
        strK=Skey.group()
        strKn=ord(strK[0])+1
        strK=chr(strKn)
        
        res1=genTree(strK+strK[-1]+'1')        
        res2=genTree(strK+strK[-1]+'2')   
        
        return([S]+res1+res2)

genTree('A1')


['A1',
 'BB1',
 'CC1',
 'DD1',
 'DD2',
 'CC2',
 'DD1',
 'DD2',
 'BB2',
 'CC1',
 'DD1',
 'DD2',
 'CC2',
 'DD1',
 'DD2']

In [59]:
import random
random.randint(3, 9)

4

In [68]:
np.random.randint(3, 9,size=[2,4])

array([[5, 7, 4, 3],
       [3, 7, 4, 5]])

In [99]:
paramR=np.random.randint(3,9,size=[2,4])
paramR[0]
Snum=set(ord('A')+paramR[0])

# it must be 4 charactors
[chr(d) for d in Snum]

['F', 'G']

In [146]:
# non duplicated charactors

Nd=3
Sd=4
paramR=np.random.randint(3,9,size=[Nd,Sd])
paramR[0]
Snum=list(set(ord('A')+paramR[0]))
while len(Snum)!=Sd:
    tmp=[ord('A')+np.random.randint(3, 9)]
    Snum=Snum+tmp
    Snum=list(set(Snum))

[chr(d) for d in Snum]

['D', 'E', 'F', 'G']

In [154]:
# non duplicated charactors

Nd=3
Sd=4 # max = 26
paramR=np.random.randint(Sd,size=[Nd,Sd])
paramR[0]
Snum=list(set(ord('A')+paramR[0]))
while len(Snum)!=Sd:
    tmp=[ord('A')+np.random.randint(Sd)]
    Snum=Snum+tmp
    Snum=list(set(Snum))

[chr(d) for d in Snum]

['A', 'B', 'C', 'D']

In [113]:
Snum+[73]

[72, 68, 70, 73]

In [92]:
Snum

{68, 69, 72}

In [169]:
Nd=3
Sd=4
def genTree(S):
    Nkey = re.search(r'\d+', S)
    Skey = re.search(r'[a-zA-Z]+', S)
    if Skey.group()[0]=='D':
        return([S])
    else:
        numK=int(Nkey.group())
        numK=numK+1
        strK=Skey.group()
        strKn=ord(strK[0])+1
        strK=chr(strKn)
        res=[]
#         Nd_tmp=np.random.randint(Nd)
#         Sd_tmp=np.random.randint(Sd)
        Nd_tmp=Nd
        Sd_tmp=Sd
        
        paramR=np.random.randint(Sd,size=[Nd_tmp,Sd_tmp])
        for k in range(len(paramR)):
            tmpS=[chr(ord('A')+d)+str(k+1) for d in paramR[k]]
#             print(k)
#             print(paramR[k])
#             print(tmpS)
            for d in tmpS:
#                 print(strK+d)
                res=res+genTree(strK+d)
            
        
        return([S]+res)

genTree('A1')


['A1',
 'BD1',
 'CD1',
 'DA1',
 'DD1',
 'DA1',
 'DB1',
 'DD2',
 'DB2',
 'DD2',
 'DB2',
 'DA3',
 'DA3',
 'DA3',
 'DA3',
 'CA1',
 'DA1',
 'DB1',
 'DC1',
 'DC1',
 'DD2',
 'DC2',
 'DC2',
 'DC2',
 'DA3',
 'DB3',
 'DA3',
 'DD3',
 'CC1',
 'DC1',
 'DA1',
 'DD1',
 'DA1',
 'DA2',
 'DB2',
 'DD2',
 'DA2',
 'DD3',
 'DA3',
 'DA3',
 'DD3',
 'CA1',
 'DA1',
 'DD1',
 'DA1',
 'DC1',
 'DB2',
 'DC2',
 'DB2',
 'DC2',
 'DB3',
 'DD3',
 'DC3',
 'DD3',
 'CB2',
 'DB1',
 'DD1',
 'DC1',
 'DC1',
 'DB2',
 'DC2',
 'DA2',
 'DD2',
 'DA3',
 'DD3',
 'DB3',
 'DB3',
 'CC2',
 'DD1',
 'DD1',
 'DD1',
 'DA1',
 'DA2',
 'DA2',
 'DC2',
 'DC2',
 'DB3',
 'DB3',
 'DD3',
 'DD3',
 'CC2',
 'DA1',
 'DC1',
 'DB1',
 'DB1',
 'DD2',
 'DA2',
 'DA2',
 'DC2',
 'DB3',
 'DA3',
 'DD3',
 'DB3',
 'CD2',
 'DA1',
 'DA1',
 'DD1',
 'DA1',
 'DB2',
 'DB2',
 'DB2',
 'DB2',
 'DC3',
 'DC3',
 'DB3',
 'DB3',
 'CA3',
 'DB1',
 'DA1',
 'DC1',
 'DB1',
 'DD2',
 'DD2',
 'DA2',
 'DB2',
 'DA3',
 'DB3',
 'DC3',
 'DA3',
 'CA3',
 'DD1',
 'DB1',
 'DC1',
 'DD1',
 'DC2',
 

In [357]:
Nd=3
Sd=4
def genTree(S):
    Nkey = re.search(r'\d+', S)
    Skey = re.search(r'[a-zA-Z]+', S)
    if Skey.group()[0]=='D':
#     if len(S)>=4:
        return([S])
    else:
        numK=int(Nkey.group())
        numK=numK+1
        strK=Skey.group()
        strKn=ord(strK[0])+1
#         strK_pre=strK
        strK=chr(strKn)
        res=[strK+'1']
        res=[]
        Nd_tmp=np.random.randint(Nd)
        Sd_tmp=np.random.randint(Sd)
#         Nd_tmp=Nd
#         Sd_tmp=Sd
        
        paramR=np.random.randint(Sd,size=[Nd_tmp,Sd_tmp])
        for k in range(len(paramR)):
            tmpS=[chr(ord('A')+d)+str(k+1) for d in paramR[k]]
#             print(k)
#             print(paramR[k])
#             print(tmpS)
            for d in tmpS:
#                 print(strK+d)
                res=res+genTree(strK+d)
            
        
        return([S]+res)

outData=genTree('A1')
print(outData)

['A1', 'BB1', 'CA1', 'DA1', 'DD1', 'DA1', 'CD1', 'CB2', 'DD1', 'DD2', 'CB2', 'BB1', 'CB1', 'DA1', 'DD1', 'DA1', 'DC2', 'DB2', 'DD2', 'CD2', 'BC1']


In [358]:
np.savetxt('data.csv', outData, header='class_name',delimiter=',',fmt='%s')

In [396]:
Nd=1
Sd=2
def genTree(S):
    Nkey = re.search(r'\d+', S)
    Skey = re.search(r'[a-zA-Z]+', S)
#     if Skey.group()[0]=='D':
    if len(S)>=4:
        return([S])
    else:
        numK=int(Nkey.group())
        numK=numK+1
        strK=Skey.group()
        strKn=ord(strK[-1])+1
        strK_pre=strK
        strK=chr(strKn)
        res=[strK+'1']
        res=[]
#         Nd_tmp=np.random.randint(Nd)
#         Sd_tmp=np.random.randint(Sd)
        Nd_tmp=Nd
        Sd_tmp=Sd
        
        paramR=np.random.randint(Sd,size=[Nd_tmp,Sd_tmp])
        paramR=np.array([[0,1],[0,1]])
        print(paramR)
        for k in range(len(paramR)):
            tmpS=[chr(ord('A')+d)+str(k+1) for d in paramR[k]]
#             print(k)
#             print(paramR[k])
            print(tmpS)
            for d in tmpS:
#                 print(strK+d)
                res=res+genTree(strK_pre+d)
            
        
        return([S]+res)

outData=genTree('A1')
print(outData)

[[0 1]
 [0 1]]
['A1', 'B1']
[[0 1]
 [0 1]]
['A1', 'B1']
['A2', 'B2']
[[0 1]
 [0 1]]
['A1', 'B1']
['A2', 'B2']
['A2', 'B2']
[[0 1]
 [0 1]]
['A1', 'B1']
['A2', 'B2']
[[0 1]
 [0 1]]
['A1', 'B1']
['A2', 'B2']
['A1', 'AA1', 'AAA1', 'AAB1', 'AAA2', 'AAB2', 'AB1', 'ABA1', 'ABB1', 'ABA2', 'ABB2', 'AA2', 'AAA1', 'AAB1', 'AAA2', 'AAB2', 'AB2', 'ABA1', 'ABB1', 'ABA2', 'ABB2']


In [443]:
# gettree 

Nd=2
Sd=3
def genTree(S):
    Nkey = re.search(r'\d+', S)
    Skey = re.search(r'[a-zA-Z]+', S)
#     if Skey.group()[0]=='D':
    if len(S)>=7:
        return([S])
    else:
        numK=int(Nkey.group())
        numK=numK+1
        strK=Skey.group()
        strKn=ord(strK[-1])+1
        strK_pre=strK
        strK=chr(strKn)
        res=[strK+'1']
        res=[]
#         Nd_tmp=np.random.randint(Nd)+1
#         Sd_tmp=np.random.randint(Sd)+1
        Nd_tmp=Nd
        Sd_tmp=Sd
        
#         paramR=np.random.randint(Sd,size=[Nd_tmp,Sd_tmp])
        paramR=np.array([[0,1],[0,1]])
#         print(paramR)
        for k in range(len(paramR)):
            tmpS=[chr(ord('A')+d)+str(k+1) for d in list(set(paramR[k]))]
#             print(k)
#             print(paramR[k])
#             print(tmpS)
            for d in tmpS:
#                 print(strK+d)
                res=res+genTree(strK_pre+d)
            
        
        return([S]+res)

outData=genTree('A1')
print(outData)

['A1', 'AA1', 'AAA1', 'AAB1', 'AAA2', 'AAB2', 'AB1', 'ABA1', 'ABB1', 'ABA2', 'ABB2', 'AA2', 'AAA1', 'AAB1', 'AAA2', 'AAB2', 'AB2', 'ABA1', 'ABB1', 'ABA2', 'ABB2']


In [447]:
dictD={}
dictD['A1']=['AA1']
dictD

{'A1': ['AA1']}

In [583]:
# getTree  Length <= 5

Nd=2
Sd=3

def dictMerge(d1,d2):
    d1c=d1.copy()
    d2c=d2.copy()
    cKey=list(set(list(d1c.keys()))&set(list(d2c.keys())))
    for key in cKey:
        tmpL=d1c[key]+d2c[key]
        d2c[key]=list(set(tmpL))
    d1c.update(d2c)
    return(d1c)

def genTree(S):
    Nkey = re.search(r'\d+', S)
    Skey = re.search(r'[a-zA-Z]+', S)
    if len(S)>=5:
        return({})
    else:
        numK=int(Nkey.group())
        strK=Skey.group()
        strKn=ord(strK[-1])+1
        strK_pre=strK
        strK=chr(strKn)
        res=[strK+'1']
        res={}
        listT=[]
        Nd_tmp=Nd
        Sd_tmp=Sd
        
        paramR=np.array([[0,1],[0,1]])

        for k in range(len(paramR)):
            tmpS=[chr(ord('A')+d)+str(k+1) for d in list(set(paramR[k]))]
            for d in tmpS:
                res=dictMerge(res,genTree(strK_pre+d))
                listT=listT+[strK_pre+d]
        
        d0={}
        if numK==1:
            d0[S]=listT
        resD=dictMerge(d0,res)
        return(resD)

outDict=genTree('A1')
print(outDict)

{'A1': ['AA1', 'AB1', 'AA2', 'AB2'], 'AA1': ['AAA1', 'AAB1', 'AAA2', 'AAB2'], 'AAA1': ['AAAB1', 'AAAA2', 'AAAA1', 'AAAB2'], 'AAB1': ['AABB2', 'AABA2', 'AABA1', 'AABB1'], 'AB1': ['ABA1', 'ABB1', 'ABA2', 'ABB2'], 'ABA1': ['ABAB1', 'ABAA2', 'ABAB2', 'ABAA1'], 'ABB1': ['ABBA1', 'ABBA2', 'ABBB2', 'ABBB1']}


In [594]:
rNd=7
all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
rLIst=np.random.randint(len(all_Item),size=rNd)
print(all_Item)
print(rLIst)

['ABB2', 'AAAA1', 'AA2', 'ABAA2', 'AAB1', 'ABBB1', 'AB1', 'AB2', 'ABA2', 'AAA2', 'AABA1', 'ABAB2', 'ABAA1', 'ABA1', 'AABB2', 'AABA2', 'ABBA2', 'ABBB2', 'AAA1', 'ABAB1', 'AAAB1', 'AABB1', 'AAAA2', 'AA1', 'ABB1', 'AAB2', 'ABBA1', 'A1', 'AAAB2']
[ 8 21 12  4  7 23 15]


In [586]:
print(len(all_Item))

29


In [581]:
nodeSize=10
conWidth=2

network = Network(
    height="500px",  # default param = 500px
    width="500px",  # default param = 500px
    notebook=True,  # For jupyter notebook, it should be True
    bgcolor="rgb(255,255,255)",  # default color = "#ffffff" "rgb(255,255,255)"
    directed=True,   # directional graph = True, non- directinal graph = False
)
str2num=lambda S: [ord(d)-ord('A')+1 if not(str.isdecimal(d)) else int(d) for d in S ]

all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
keyList=list(outDict.keys())
for k in range(len(all_Item)):
    nd= int("".join(map(str, str2num(all_Item[k]))))
    network.add_node(n_id=nd,label=all_Item[k], shape="box",size=nodeSize)
    
for k in range(len(outDict)):
    nodeMn= int("".join(map(str, str2num(keyList[k]))))
    
    nodeS=outDict[keyList[k]]
    nodeSn=[ int("".join(map(str, str2num(d)))) for d in nodeS]
    for j in range(len(nodeSn)):
        network.add_edge(nodeMn,nodeSn[j], width=conWidth,smooth="dynamic")
    

# output the results in the HTML format (and visualization in the jupyter notebook panel)
network.show("network_disp1.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [595]:
nodeSize=10
conWidth=2

network = Network(
    height="500px",  # default param = 500px
    width="500px",  # default param = 500px
    notebook=True,  # For jupyter notebook, it should be True
    bgcolor="rgb(255,255,255)",  # default color = "#ffffff" "rgb(255,255,255)"
    directed=True,   # directional graph = True, non- directinal graph = False
)
str2num=lambda S: [ord(d)-ord('A')+1 if not(str.isdecimal(d)) else int(d) for d in S ]

all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
keyList=list(outDict.keys())
for k in range(len(all_Item)):
    nd= int("".join(map(str, str2num(all_Item[k]))))
    if k in rLIst:
        colName="red"
    else:
        colName="gray"
    network.add_node(n_id=nd,label=all_Item[k], shape="box",size=nodeSize,color =colName)
    
for k in range(len(outDict)):
    nodeMn= int("".join(map(str, str2num(keyList[k]))))
    
    nodeS=outDict[keyList[k]]
    nodeSn=[ int("".join(map(str, str2num(d)))) for d in nodeS]
    for j in range(len(nodeSn)):
        network.add_edge(nodeMn,nodeSn[j], width=conWidth,smooth="dynamic")
    

# output the results in the HTML format (and visualization in the jupyter notebook panel)
network.show("network_disp1.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [577]:
# getTree  Length < 6

Nd=2
Sd=3

def dictMerge(d1,d2):
    d1c=d1.copy()
    d2c=d2.copy()
    cKey=list(set(list(d1c.keys()))&set(list(d2c.keys())))
    for key in cKey:
        tmpL=d1c[key]+d2c[key]
        d2c[key]=list(set(tmpL))
    d1c.update(d2c)
    return(d1c)

def genTree(S):
    Nkey = re.search(r'\d+', S)
    Skey = re.search(r'[a-zA-Z]+', S)
#     if Skey.group()[0]=='D':
    if len(S)>=6:
#         d0={}
#         d0[S]=['']
#         return(d0)
        return({})
    else:
        numK=int(Nkey.group())
#         numK=numK+1
        strK=Skey.group()
        strKn=ord(strK[-1])+1
        strK_pre=strK
        strK=chr(strKn)
        res=[strK+'1']
        res={}
        listT=[]
#         Nd_tmp=np.random.randint(Nd)+1
#         Sd_tmp=np.random.randint(Sd)+1
        Nd_tmp=Nd
        Sd_tmp=Sd
        
#         paramR=np.random.randint(Sd,size=[Nd_tmp,Sd_tmp])
        paramR=np.array([[0,1],[0,1]])
#         print(paramR)
        for k in range(len(paramR)):
            tmpS=[chr(ord('A')+d)+str(k+1) for d in list(set(paramR[k]))]
#             print(k)
#             print(paramR[k])
#             print(tmpS)
            for d in tmpS:
#                 print(strK+d)
                res=dictMerge(res,genTree(strK_pre+d))
                listT=listT+[strK_pre+d]
#                 print(res)
        
        d0={}
        if numK==1:
            d0[S]=listT
        resD=dictMerge(d0,res)
#         resD=d0
        return(resD)

outDict=genTree('A1')
print(outDict)

{'A1': ['AA1', 'AB1', 'AA2', 'AB2'], 'AA1': ['AAA1', 'AAB1', 'AAA2', 'AAB2'], 'AAA1': ['AAAB1', 'AAAA2', 'AAAA1', 'AAAB2'], 'AAAA1': ['AAAAA2', 'AAAAB1', 'AAAAA1', 'AAAAB2'], 'AAAB1': ['AAABA1', 'AAABB2', 'AAABB1', 'AAABA2'], 'AAB1': ['AABB2', 'AABA2', 'AABA1', 'AABB1'], 'AABA1': ['AABAB1', 'AABAA2', 'AABAB2', 'AABAA1'], 'AABB1': ['AABBB1', 'AABBA1', 'AABBA2', 'AABBB2'], 'AB1': ['ABA1', 'ABB1', 'ABA2', 'ABB2'], 'ABA1': ['ABAB1', 'ABAA2', 'ABAB2', 'ABAA1'], 'ABAA1': ['ABAAA1', 'ABAAB2', 'ABAAB1', 'ABAAA2'], 'ABAB1': ['ABABA2', 'ABABA1', 'ABABB2', 'ABABB1'], 'ABB1': ['ABBA1', 'ABBA2', 'ABBB2', 'ABBB1'], 'ABBA1': ['ABBAB1', 'ABBAB2', 'ABBAA1', 'ABBAA2'], 'ABBB1': ['ABBBA1', 'ABBBB1', 'ABBBA2', 'ABBBB2']}


In [518]:
print(len(outDict))
print(outDict.keys())
print(outDict.values())

list(set(list(outDict.keys())+sum(outDict.values(), [])))

5
dict_keys(['A1', 'AA1', 'AB1', 'AA2', 'AB2'])
dict_values([['AA1', 'AB1', 'AA2', 'AB2'], ['AAA1', 'AAB1', 'AAA2', 'AAB2'], ['ABA1', 'ABB1', 'ABA2', 'ABB2'], ['AAA1', 'AAB1', 'AAA2', 'AAB2'], ['ABA1', 'ABB1', 'ABA2', 'ABB2']])


{'A1',
 'AA1',
 'AA2',
 'AAA1',
 'AAA2',
 'AAB1',
 'AAB2',
 'AB1',
 'AB2',
 'ABA1',
 'ABA2',
 'ABB1',
 'ABB2'}

In [526]:
keyList=list(outDict.keys())
keyList

['A1', 'AA1', 'AB1', 'AA2', 'AB2']

In [532]:
str.isdecimal('1'),str.isdecimal('A')

(True, False)

In [540]:
str2num=lambda S: [ord(d)-ord('A')+1 if not(str.isdecimal(d)) else int(d) for d in S ]

outL=str2num('AA1')
outN = int("".join(map(str, outL)))

print(outL)
print(outN)

[1, 1, 1]
111


In [578]:
nodeSize=10
conWidth=2

network = Network(
    height="500px",  # default param = 500px
    width="500px",  # default param = 500px
    notebook=True,  # For jupyter notebook, it should be True
    bgcolor="rgb(255,255,255)",  # default color = "#ffffff" "rgb(255,255,255)"
    directed=True,   # directional graph = True, non- directinal graph = False
)
str2num=lambda S: [ord(d)-ord('A')+1 if not(str.isdecimal(d)) else int(d) for d in S ]

all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))
keyList=list(outDict.keys())
for k in range(len(all_Item)):
    nd= int("".join(map(str, str2num(all_Item[k]))))
    network.add_node(n_id=nd,label=all_Item[k], shape="box",size=nodeSize)
    
for k in range(len(outDict)):
    nodeMn= int("".join(map(str, str2num(keyList[k]))))
    
    nodeS=outDict[keyList[k]]
    nodeSn=[ int("".join(map(str, str2num(d)))) for d in nodeS]
    for j in range(len(nodeSn)):
        network.add_edge(nodeMn,nodeSn[j], width=conWidth,smooth="dynamic")
    

# output the results in the HTML format (and visualization in the jupyter notebook panel)
network.show("class_list1.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [568]:
# completed version of making a network of class nodes

Nd=2
Sd=3

def dictMerge(d1,d2):
    d1c=d1.copy()
    d2c=d2.copy()
    cKey=list(set(list(d1c.keys()))&set(list(d2c.keys())))
    for key in cKey:
        tmpL=d1c[key]+d2c[key]
        d2c[key]=list(set(tmpL))
    d1c.update(d2c)
    return(d1c)

def genTree(S):
    Nkey = re.search(r'\d+', S)
    Skey = re.search(r'[a-zA-Z]+', S)
    if len(S)>=7:
        return({})
    else:
        numK=int(Nkey.group())
#         numK=numK+1
        strK=Skey.group()
        strKn=ord(strK[-1])+1
        strK_pre=strK
        strK=chr(strKn)
        res=[strK+'1']
        res={}
        listT=[]
#         Nd_tmp=np.random.randint(Nd)+1
#         Sd_tmp=np.random.randint(Sd)+1
        Nd_tmp=Nd
        Sd_tmp=Sd
        
#         paramR=np.random.randint(Sd,size=[Nd_tmp,Sd_tmp])
        paramR=np.array([[0,1],[0,1]])
        for k in range(len(paramR)):
            tmpS=[chr(ord('A')+d)+str(k+1) for d in list(set(paramR[k]))]
            for d in tmpS:
                res=dictMerge(res,genTree(strK_pre+d))
                listT=listT+[strK_pre+d]
        
        d0={}
        if numK==1:
            d0[S]=listT
        resD=dictMerge(d0,res)
        return(resD)

outDict=genTree('A1')
print(outDict)

{'A1': ['AA1', 'AB1', 'AA2', 'AB2'], 'AA1': ['AAA1', 'AAB1', 'AAA2', 'AAB2'], 'AAA1': ['AAAB1', 'AAAA2', 'AAAA1', 'AAAB2'], 'AAAA1': ['AAAAA2', 'AAAAB1', 'AAAAA1', 'AAAAB2'], 'AAAAA1': ['AAAAAB2', 'AAAAAA2', 'AAAAAA1', 'AAAAAB1'], 'AAAAB1': ['AAAABA1', 'AAAABA2', 'AAAABB1', 'AAAABB2'], 'AAAB1': ['AAABA1', 'AAABB2', 'AAABB1', 'AAABA2'], 'AAABA1': ['AAABAB2', 'AAABAA2', 'AAABAB1', 'AAABAA1'], 'AAABB1': ['AAABBA1', 'AAABBB1', 'AAABBB2', 'AAABBA2'], 'AAB1': ['AABB2', 'AABA2', 'AABA1', 'AABB1'], 'AABA1': ['AABAB1', 'AABAA2', 'AABAB2', 'AABAA1'], 'AABAA1': ['AABAAB1', 'AABAAB2', 'AABAAA2', 'AABAAA1'], 'AABAB1': ['AABABA1', 'AABABB2', 'AABABB1', 'AABABA2'], 'AABB1': ['AABBB1', 'AABBA1', 'AABBA2', 'AABBB2'], 'AABBA1': ['AABBAA2', 'AABBAB2', 'AABBAB1', 'AABBAA1'], 'AABBB1': ['AABBBA1', 'AABBBA2', 'AABBBB1', 'AABBBB2'], 'AB1': ['ABA1', 'ABB1', 'ABA2', 'ABB2'], 'ABA1': ['ABAB1', 'ABAA2', 'ABAB2', 'ABAA1'], 'ABAA1': ['ABAAA1', 'ABAAB2', 'ABAAB1', 'ABAAA2'], 'ABAAA1': ['ABAAAA1', 'ABAAAB1', 'ABAAAA

In [552]:
keyList

['A1', 'AA1', 'AAA1', 'AAB1', 'AB1', 'ABA1', 'ABB1']

In [569]:
nodeSize=10
conWidth=2

network = Network(
    height="500px",  # default param = 500px
    width="1000px",  # default param = 500px
    notebook=True,  # For jupyter notebook, it should be True
    bgcolor="rgb(255,255,255)",  # default color = "#ffffff" "rgb(255,255,255)"
    directed=True,   # directional graph = True, non- directinal graph = False
)
str2num=lambda S: [ord(d)-ord('A')+1 if not(str.isdecimal(d)) else int(d) for d in S ]

all_Item=list(set(list(outDict.keys())+sum(outDict.values(), [])))

keyList=list(outDict.keys())
for k in range(len(all_Item)):
    nd= int("".join(map(str, str2num(all_Item[k]))))
    network.add_node(n_id=nd,label=all_Item[k], shape="box",size=nodeSize)
    
for k in range(len(outDict)):
    nodeMn= int("".join(map(str, str2num(keyList[k]))))
#     print(keyList[k])
    nodeS=outDict[keyList[k]]
#     print(nodeS)
    nodeSn=[ int("".join(map(str, str2num(d)))) for d in nodeS]
#     print(nodeSn)
    for j in range(len(nodeSn)):
        network.add_edge(nodeMn,nodeSn[j], width=conWidth,smooth="dynamic")

# output the results in the HTML format (and visualization in the jupyter notebook panel)
network.show("class_list2.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [461]:
dict1 = {'t1': 1, 't2': 2}
dict2 = {'t1': 50, 't3': 2, 't4': 5}

cKey=list(set(list(dict1.keys()))&set(list(dict2.keys())))

dict1.update(dict2)
print(dict1)

print(cKey)


{'t1': 50, 't2': 2, 't3': 2, 't4': 5}
['t1']


In [480]:
def dictMerge(d1,d2):
    d1c=d1.copy()
    d2c=d2.copy()
    cKey=list(set(list(d1c.keys()))&set(list(d2c.keys())))
    for key in cKey:
        d2c[key]=d1c[key]+d2c[key]
    d1c.update(d2c)
    return(d1c)

dict1 = {'t1': [1], 't2': [2]}
dict2 = {'t1': [50], 't3':[2] , 't4': [5]}

dict3=dictMerge(dict1,dict2)

print(dict1)
print(dict2)
print(dict3)


{'t1': [1], 't2': [2]}
{'t1': [50], 't3': [2], 't4': [5]}
{'t1': [1, 50], 't2': [2], 't3': [2], 't4': [5]}


In [484]:
def dictMerge(d1,d2):
    d1c=d1.copy()
    d2c=d2.copy()
    cKey=list(set(list(d1c.keys()))&set(list(d2c.keys())))
    for key in cKey:
        d2c[key]=d1c[key]+d2c[key]
    d1c.update(d2c)
    return(d1c)

dict1 = {'t1': ['']}
dict2 = {'t1': ['']}

dict3=dictMerge(dict1,dict2)

print(dict1)
print(dict2)
print(dict3)


{'t1': ['']}
{'t1': ['']}
{'t1': ['', '']}


In [394]:
strK='B'
paramR=np.array([[0,1]])
print(paramR)
for k in range(len(paramR)):
    tmpS=[chr(ord('A')+d)+str(k+1) for d in paramR[k]]
#             print(k)
#             print(paramR[k])
    print(tmpS)
    for d in tmpS:
        print(strK+d)
#         res=res+genTree(strK+d)

[[0 1]]
['A1', 'B1']
BA1
BB1


In [510]:
from pyvis.network import Network

# network instance generation 
network = Network(
    height="350px",  # default param = 500px
    width="450px",  # default param = 500px
    notebook=True,  # For jupyter notebook, it should be True
    bgcolor="rgb(255,255,255)",  # default color = "#ffffff" "rgb(0,0,0)"
    directed=True,   # directional graph = True, non- directinal graph = False
)

# Node increment "add_node"
# "label"  is not necessary. It will be the same as ID if there is no setting 
network.add_node(n_id=1, label="1", shape="triangle",size=10)
network.add_node(n_id=2, label="2", shape="circle", color="rgb(255,170,170)", size=10, labelHighlightBold=True)
network.add_node(n_id=3, label="3", shape="box")
network.add_node(n_id=4, label="4", shape="circle")  # default shape  = "dot" 
network.add_node(n_id=5, label="5", shape="circle")  # default shape  = "dot" 

#  connecting nodes by "add_edge" 
network.add_edge(1, 2)
network.add_edge(2, 4, width=2)  # "width" determines the size of the object
network.add_edge(3, 4, smooth="dynamic")  # "smooth" changes the corners smoothly 
network.add_edge(4, 3, smooth="dynamic")  # setting is updated if it is a bi-directional
# network.add_edge(3, 4, smooth="straightCross")  # "smooth" changes the corners smoothly 
# network.add_edge(4, 3, smooth="straightCross")  # setting is updated if it is a bi-directional
network.add_edge(5, 2)

# output the results in the HTML format (and visualization in the jupyter notebook panel)
network.show("pyvis_sample1.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [511]:
nodeSize=10
conWidth=2

network = Network(
    height="500px",  # default param = 500px
    width="500px",  # default param = 500px
    notebook=True,  # For jupyter notebook, it should be True
    bgcolor="rgb(255,255,255)",  # default color = "#ffffff" "rgb(255,255,255)"
    directed=True,   # directional graph = True, non- directinal graph = False
)

# Node increment "add_node"
# "label"  is not necessary. It will be the same as ID if there is no setting 
network.add_node(n_id=0, level=1,label="root", shape="box",size=nodeSize*10)
network.add_node(n_id=1, level=1,label="A", shape="box",size=nodeSize)
network.add_node(n_id=2, level=1,label="B", shape="box",size=nodeSize)
network.add_node(n_id=3, level=1,label="C", shape="box",size=nodeSize)

network.add_node(n_id=11, level=2,label="AA", shape="box",size=nodeSize)
network.add_node(n_id=21, level=2,label="BA", shape="box",size=nodeSize)
network.add_node(n_id=22, level=2,label="BB", shape="box",size=nodeSize)
network.add_node(n_id=31, level=2,label="CA", shape="box",size=nodeSize)

network.add_node(n_id=111, level=3,label="AAA", shape="box",size=nodeSize)
network.add_node(n_id=221, level=3,label="BBA", shape="box",size=nodeSize)

network.add_edge(0,1, width=conWidth,smooth="dynamic")
network.add_edge(0,2, width=conWidth,smooth="dynamic")
network.add_edge(0,3, width=conWidth,smooth="dynamic")

network.add_edge(1,11, width=conWidth)
network.add_edge(2, 21, width=conWidth)
network.add_edge(2, 22, width=conWidth)
network.add_edge(3,31, width=conWidth)
network.add_edge(11,111, width=conWidth)
network.add_edge(22, 221, width=conWidth)

# output the results in the HTML format (and visualization in the jupyter notebook panel)
network.show("hierarchical1.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [244]:
network.nodes

[{'color': '#97c2fc',
  'level': 1,
  'size': 100,
  'id': 0,
  'label': 'root',
  'shape': 'box'},
 {'color': '#97c2fc',
  'level': 1,
  'size': 10,
  'id': 1,
  'label': 'A',
  'shape': 'box'},
 {'color': '#97c2fc',
  'level': 1,
  'size': 10,
  'id': 2,
  'label': 'B',
  'shape': 'box'},
 {'color': '#97c2fc',
  'level': 1,
  'size': 10,
  'id': 3,
  'label': 'C',
  'shape': 'box'},
 {'color': '#97c2fc',
  'level': 2,
  'size': 10,
  'id': 11,
  'label': 'AA',
  'shape': 'box'},
 {'color': '#97c2fc',
  'level': 2,
  'size': 10,
  'id': 21,
  'label': 'BA',
  'shape': 'box'},
 {'color': '#97c2fc',
  'level': 2,
  'size': 10,
  'id': 22,
  'label': 'BB',
  'shape': 'box'},
 {'color': '#97c2fc',
  'level': 2,
  'size': 10,
  'id': 31,
  'label': 'CA',
  'shape': 'box'},
 {'color': '#97c2fc',
  'level': 3,
  'size': 10,
  'id': 111,
  'label': 'AAA',
  'shape': 'box'},
 {'color': '#97c2fc',
  'level': 3,
  'size': 10,
  'id': 221,
  'label': 'BBA',
  'shape': 'box'}]

In [289]:
import networkx as nx

Graph1 = nx.DiGraph()
nx.add_path(Graph1, [2,4, 3, 1, 0, 3, 8, 7, 6, 9])  # 2→ 4→ 3→ 1→ 0→ 3→ 8→ 7→ 6→  9
nx.add_path(Graph1, [4, 0, 5, 3, 1, 6, 2, 8, 9, 4])  # 4→ 0→ 5→ 3→ 1→ 6→ 2→ 8→ 9→ 4

network1 = Network(
    height="500px",  # default param = 500px
    width="500px",  # default param = 500px
    notebook=True,  # For jupyter notebook, it should be True
    bgcolor="rgb(255,255,255)",  # default color = "#ffffff" "rgb(255,255,255)"
    directed=True,   # directional graph = True, non- directinal graph = False
)

network1.from_nx(Graph1)

for k in range(len(network.nodes)):
    tmpN=network1.nodes[k]['label']
    network1.nodes[k]['label']=str(tmpN)
    network1.nodes[k]['shape']='box'
    network1.nodes[k]['color']='#eeeeff'
    
network1.show("output_nx_network1.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [254]:
# https://stackoverflow.com/questions/72819127/pyvis-hierarchical-layout-not-displaying-correctly-when-many-edges-are-added

from pyvis.network import Network
import networkx as nx
import matplotlib.pyplot as plt

ddd = {'a', 'b', 'c'}
ccc = {'p', 'q', 'r'}
yyy = {'x', 'y', 'z'}
edge_list_tuples = [('a', 'q'), ('b', 'p'), ('b', 'q'), ('p', 'y'), ('r', 'y'), ('r', 'z'), ('x', 'x')]
g = nx.Graph()
pyvs = Network(notebook=True, height = "100%", width = "100%", layout=True)

g.add_nodes_from(yyy, bipartite="yy")
g.add_nodes_from(ccc, bipartite="cc")
g.add_nodes_from(ddd, bipartite="dd")
g.add_edges_from(edge_list_tuples)

color_map = nx.get_node_attributes(g, "bipartite")

for key in color_map:
    if color_map[key] == "dd":
        color_map[key] = "yellow"
        lvl = 3
    if color_map[key] == "cc":
        color_map[key] = "green"
        lvl = 2
    if color_map[key] == "yy":
        color_map[key] = "blue"
        lvl = 1
    pyvs.add_node(key, color=color_map[key], level=lvl)

pyvs.add_edges(g.edges()) # The nodes should exist. Unlike in networkx. 
pyvs.show_buttons(filter_=['physics'])
pyvs.show("output_network.html")

Local cdn resources have problems on chrome/safari when used in jupyter-notebook. 


In [275]:
network.nodes
for k in range(len(network.nodes)):
    network.nodes[k]['label']=str(k)
network.show("output_network2.html")

In [271]:
s1={'color': '#97c2fc', 'size': 10, 'id': 3, 'label': "3", 'shape': 'dot'}
s1['color']

'#97c2fc'

In [273]:
network.nodes[0]['label']

'3'

In [268]:
network.nodes[0]={'color': '#97c2fc', 'size': 10, 'id': 3, 'label': "3", 'shape': 'dot'}
network.show("output_network2.html")